'use strict';

// Gerechten per land voor de wereldkeuken, op landcode.
// Een gerecht is 'naam|omschrijving|soort|tijd|maaltijden', met soort l (vlees), v (vis) of g (vegetarisch),
// tijd s (snel), n (gemiddeld) of u (uitgebreid) en maaltijden o, m en a (weggelaten betekent avondeten).
// De gerechten per land zijn een eigen keuze van bekende gerechten, geen officiele ranglijst.
Object.assign(WORLD_DISHES, {
  NL: [
    'Stamppot boerenkool|aardappelpuree met boerenkool en rookworst|l|n',
    'Erwtensoep|dikke soep van spliterwten met rookworst|l|u|ma',
    'Hutspot|stamppot van aardappel, wortel en ui|l|n',
    'Pannenkoeken|grote dunne pannenkoeken, zoet of hartig|g|n|ma',
    'Kibbeling|gefrituurde stukjes witvis met saus|v|s|ma',
    'Hollandse nieuwe|rauwe haring met uitjes|v|s|m',
    'Bitterballen|krokante ragoutballetjes met mosterd|l|s|m',
    'Poffertjes|kleine luchtige pannenkoekjes met poedersuiker|g|n|m',
    'Hachee|stoofvlees met veel ui en laurier|l|u',
    'Broodje kroket|zacht broodje met een rundvleeskroket|l|s|m',
  ],
  BE: [
    'Stoofvlees met friet|rundvlees gestoofd in bier, met frieten|l|u',
    'Mosselen met friet|gekookte mosselen met frieten|v|n',
    'Waterzooi|romige stoofpot met kip en groenten|l|u',
    'Witlof met ham en kaas|witlof in ham gerold, met kaassaus uit de oven|l|u',
    'Vol-au-vent|bladerdeegbakje met kipragout|l|u',
    'Konijn met pruimen|konijn gestoofd met pruimen|l|u',
    'Tomaat-garnaal|tomaat gevuld met grijze garnalen|v|s|m',
    'Balletjes in tomatensaus|gehaktballetjes in tomatensaus|l|n',
    'Stoemp met worst|aardappelpuree met groenten en braadworst|l|n',
    'Luikse wafels|zoete wafels met parelsuiker|g|n|om',
  ],
  FR: [
    'Coq au vin|kip gestoofd in rode wijn|l|u',
    'Boeuf bourguignon|rundvlees gestoofd in rode wijn|l|u',
    'Ratatouille|gestoofde groenten uit de Provence|g|n',
    'Quiche lorraine|hartige taart met spek en ei|l|u|ma',
    'Croque-monsieur|tosti met ham, kaas en bechamelsaus|l|s|m',
    'Bouillabaisse|vissoep uit Marseille|v|u',
    'Cassoulet|stoofpot van witte bonen, worst en eend|l|u',
    'Crêpes|dunne pannenkoeken, zoet of hartig|g|n|om',
    'Franse uiensoep|soep van gekarameliseerde ui met kaasbroodje|l|u|ma',
    'Tartiflette|aardappelgratin met spek en kaas|l|u',
  ],
  IT: [
    'Pizza margherita|pizza met tomaat, mozzarella en basilicum|g|n',
    'Spaghetti carbonara|pasta met ei, spek en pecorino|l|s',
    'Lasagne|laagjes pasta met gehaktsaus en bechamel|l|u',
    'Risotto met paddenstoelen|romige rijst met paddenstoelen|g|n',
    'Spaghetti bolognese|pasta met saus van gehakt en tomaat|l|n',
    'Gnocchi|aardappelknoedels met saus|g|n',
    'Ossobuco|kalfsschenkel gestoofd met groenten|l|u',
    'Minestrone|stevige groentesoep met pasta|g|n|ma',
    'Parmigiana di melanzane|ovenschotel van aubergine, tomaat en kaas|g|u',
    'Saltimbocca|kalfsvlees met ham en salie|l|s',
  ],
  ES: [
    'Paella|rijst met saffraan, kip en zeevruchten|v|u',
    'Tortilla española|dikke omelet met aardappel en ui|g|n|ma',
    'Gazpacho|koude soep van tomaat en groenten|g|s|m',
    'Patatas bravas|gebakken aardappels met pittige saus|g|n|m',
    'Gambas al ajillo|garnalen in knoflookolie|v|s',
    'Pulpo a la gallega|octopus met paprikapoeder en aardappel|v|u',
    'Albondigas|gehaktballetjes in tomatensaus|l|n',
    'Fabada asturiana|stoofpot van witte bonen en worst|l|u',
    'Croquetas|kroketjes met ham|l|n|m',
    'Pisto|gestoofde groenten met een ei|g|n',
  ],
  PT: [
    'Bacalhau à brás|kabeljauw met aardappel en ei|v|n',
    'Caldo verde|soep van aardappel, kool en chorizo|l|n|ma',
    'Francesinha|sandwich met vlees, kaas en biersaus|l|n',
    'Sardinhas assadas|gegrilde sardines|v|s',
    'Arroz de marisco|rijst met zeevruchten|v|u',
    'Cozido à portuguesa|stoofpot van vlees, worst en groenten|l|u',
    'Frango piri-piri|gegrilde kip met pittige saus|l|u',
    'Bifana|broodje met gemarineerd varkensvlees|l|s|m',
    'Polvo à lagareiro|octopus uit de oven met aardappel|v|u',
    'Pastel de nata|bladerdeegtaartje met custard|g|u|om',
  ],
  DE: [
    'Schnitzel|gepaneerde lap kalfs- of varkensvlees|l|n',
    'Bratwurst met zuurkool|braadworst met zuurkool en mosterd|l|n',
    'Sauerbraten|gemarineerd rundvlees, lang gestoofd|l|u',
    'Käsespätzle|eiernoedels met kaas en gebakken ui|g|n',
    'Currywurst|worst met curryketchup en friet|l|s|ma',
    'Kartoffelsalat|aardappelsalade met spek|l|n|ma',
    'Rouladen|rundvleesrolletjes met spek en augurk|l|u',
    'Maultaschen|gevulde deegkussentjes|l|n',
    'Eisbein|gekookte varkensschenkel met zuurkool|l|u',
    'Flammkuchen|dunne bodem met zure room, ui en spek|l|n',
  ],
  GB: [
    'Fish and chips|gefrituurde vis met dikke frieten|v|n',
    'Full English breakfast|eieren, spek, worst, bonen en toast|l|n|o',
    'Shepherd\'s pie|lamsgehakt met een laag aardappelpuree|l|u',
    'Sunday roast|gebraden vlees met groenten en jus|l|u',
    'Chicken tikka masala|kip in romige tomaten-kerriesaus|l|n',
    'Bangers and mash|worstjes met aardappelpuree en uienjus|l|n',
    'Beef Wellington|ossenhaas in bladerdeeg|l|u',
    'Cornish pasty|deegflap gevuld met vlees en groenten|l|u|ma',
    'Toad in the hole|worstjes in gebakken beslag|l|u',
    'Scones met jam|luchtige broodjes met room en jam|g|n|om',
  ],
  GR: [
    'Moussaka|ovenschotel met aubergine en gehakt|l|u',
    'Souvlaki|vleesspiesjes met pitabrood|l|n',
    'Gyros|geroosterd vlees in pitabrood|l|s|ma',
    'Griekse salade|tomaat, komkommer, olijven en feta|g|s|ma',
    'Spanakopita|bladerdeegtaart met spinazie en feta|g|u|ma',
    'Pastitsio|pastaschotel met gehakt en bechamel|l|u',
    'Dolmades|wijnbladeren gevuld met rijst|g|u|m',
    'Gemista|tomaten en paprika gevuld met rijst|g|u',
    'Stifado|rundvlees gestoofd met zilveruitjes|l|u',
    'Tzatziki met brood|yoghurtdip met komkommer en knoflook|g|s|m',
  ],
  TR: [
    'Döner kebab|geroosterd vlees van het spit|l|s|ma',
    'Lahmacun|dunne Turkse pizza met gehakt|l|n|ma',
    'Köfte|gekruide gehaktballetjes van de grill|l|n',
    'İskender kebab|döner op brood met tomatensaus en yoghurt|l|n',
    'Menemen|roerei met tomaat en paprika|g|s|o',
    'Mantı|kleine gevulde deegkussentjes met yoghurt|l|u',
    'Pide|bootvormig brood met vulling|l|n',
    'İmam bayıldı|gevulde aubergine met ui en tomaat|g|u',
    'Mercimek çorbası|soep van rode linzen|g|n|ma',
    'Börek|bladerdeeg met kaas en spinazie|g|u|om',
  ],
  LB: [
    'Falafel|gefrituurde balletjes van kikkererwten|g|n|ma',
    'Hummus|puree van kikkererwten en tahin|g|s|m',
    'Tabouleh|salade van peterselie, bulgur en tomaat|g|s|m',
    'Shoarma|gekruid vlees in pitabrood|l|n|ma',
    'Kibbeh|gehakt met bulgur, gefrituurd|l|u',
    'Fattoush|salade met gebakken pitabrood|g|s|m',
    'Manakish|plat brood met za\'atar of kaas|g|n|om',
    'Baba ganoush|puree van geroosterde aubergine|g|n|m',
    'Kafta|gekruide gehaktspiesjes|l|n',
    'Mujaddara|linzen met rijst en gebakken ui|g|n',
  ],
  IN: [
    'Butter chicken|kip in romige tomatensaus|l|u',
    'Biryani|gekruide rijst met vlees|l|u',
    'Dal|gekruide stoof van linzen|g|n',
    'Palak paneer|spinaziecurry met verse kaas|g|n',
    'Tandoori chicken|gemarineerde kip uit de oven|l|u',
    'Chana masala|curry van kikkererwten|g|n',
    'Samosa|gefrituurd deegpakketje met aardappel|g|u|m',
    'Masala dosa|krokante pannenkoek met aardappelvulling|g|u|om',
    'Rogan josh|lamscurry uit Kasjmir|l|u',
    'Aloo gobi|curry van aardappel en bloemkool|g|n',
  ],
  CN: [
    'Pekingeend|geroosterde eend met pannenkoekjes|l|u',
    'Dumplings|gestoomde of gebakken deegpakketjes|l|u|ma',
    'Kung pao kip|roerbak van kip, pinda\'s en chilipeper|l|s',
    'Mapo tofu|tofu in pittige saus met gehakt|l|n',
    'Zoetzuur varkensvlees|krokant varkensvlees in zoetzure saus|l|n',
    'Gebakken rijst|rijst uit de wok met ei en groenten|g|s',
    'Chow mein|gebakken noedels met groenten|g|s',
    'Hot pot|samen koken in een pan bouillon|l|u',
    'Loempia\'s|gefrituurde rolletjes met groenten|g|u|m',
    'Wontonsoep|bouillon met gevulde deegkussentjes|l|n|ma',
  ],
  JP: [
    'Sushi|rijst met rauwe vis of groenten|v|u',
    'Ramen|noedelsoep met bouillon en toppings|l|u',
    'Tempura|garnalen en groenten in luchtig beslag|v|n',
    'Tonkatsu|gepaneerde varkenskotelet|l|n',
    'Okonomiyaki|hartige pannenkoek met kool|l|n',
    'Yakitori|kipspiesjes van de grill|l|n',
    'Udon|dikke noedels in bouillon|v|n',
    'Japanse curry|milde curry met rijst|l|n',
    'Gyoza|gebakken dumplings|l|u|ma',
    'Misosoep|soep van misopasta met tofu|v|s|om',
  ],
  KR: [
    'Bibimbap|rijst met groenten, ei en chilipasta|g|n',
    'Bulgogi|gemarineerd rundvlees van de grill|l|n',
    'Kimchi jjigae|stoofpot van kimchi met tofu|l|n',
    'Koreaanse gefrituurde kip|krokante kip met zoet-pittige saus|l|u',
    'Japchae|glasnoedels met groenten|g|n',
    'Tteokbokki|rijstcakes in pittige saus|v|s|ma',
    'Kimbap|rijstrollen met groenten in zeewier|g|n|m',
    'Samgyeopsal|gegrild buikspek met sla|l|n',
    'Sundubu jjigae|pittige soep met zachte tofu|v|n',
    'Pajeon|hartige pannenkoek met lente-ui|g|s|ma',
  ],
  TH: [
    'Pad thai|gebakken rijstnoedels met ei en pinda\'s|l|s',
    'Groene curry|curry met kokosmelk en kip|l|n',
    'Tom yum|pittig-zure soep met garnalen|v|n',
    'Massaman curry|milde curry met aardappel en pinda\'s|l|u',
    'Som tam|pittige salade van groene papaja|v|s|m',
    'Pad kra pao|roerbak met basilicum en gehakt|l|s',
    'Tom kha gai|kokossoep met kip|l|n',
    'Khao pad|Thaise gebakken rijst|l|s',
    'Rode curry|pittige curry met kokosmelk|l|n',
    'Mango met kleefrijst|zoete rijst met mango|g|n|m',
  ],
  VN: [
    'Pho|noedelsoep met rundvlees en kruiden|l|u',
    'Banh mi|stokbrood met vlees en ingelegde groenten|l|s|m',
    'Verse loempia\'s|rijstvelrolletjes met garnalen en kruiden|v|n|m',
    'Bun cha|gegrild varkensvlees met noedels|l|n',
    'Com tam|gebroken rijst met gegrild vlees|l|n',
    'Bun bo Hue|pittige noedelsoep met rundvlees|l|u',
    'Banh xeo|krokante pannenkoek met garnalen|v|n',
    'Cha gio|gefrituurde loempia\'s|l|u|m',
    'Ca kho to|vis gestoofd in karamelsaus|v|u',
    'Goi ga|frisse salade met kip en kruiden|l|s|m',
  ],
  ID: [
    'Nasi goreng|gebakken rijst met ketjap en ei|l|n',
    'Saté|vleesspiesjes met pindasaus|l|n',
    'Rendang|rundvlees lang gestoofd in kokos en kruiden|l|u',
    'Gado gado|groenten met pindasaus|g|n',
    'Bami goreng|gebakken noedels met groenten|l|n',
    'Soto ayam|kippensoep met kurkuma|l|u|ma',
    'Bakso|soep met gehaktballetjes|l|n|ma',
    'Ayam goreng|gefrituurde gemarineerde kip|l|u',
    'Sambal goreng boontjes|pittige roergebakken boontjes|v|s',
    'Tempeh goreng|gebakken tempeh|g|s',
  ],
  MA: [
    'Tajine met kip|kip gestoofd met citroen en olijven|l|u',
    'Couscous|couscous met groenten en vlees|l|u',
    'Harira|soep van tomaat, linzen en kikkererwten|l|u|ma',
    'Pastilla|hartig-zoete taart met kip en amandel|l|u',
    'Kefta tajine|gehaktballetjes in tomatensaus met ei|l|n',
    'Zaalouk|salade van gestoofde aubergine|g|n|m',
    'Mechoui|langzaam geroosterd lamsvlees|l|u',
    'Bissara|soep van gedroogde tuinbonen|g|u|om',
    'Msemen|gevouwen pannenkoeken|g|u|o',
    'Sardines met chermoula|sardines met kruidenmarinade|v|n',
  ],
  EG: [
    'Koshari|rijst, linzen en pasta met tomatensaus|g|u',
    'Ful medames|gestoofde tuinbonen|g|u|o',
    'Ta\'ameya|falafel van tuinbonen|g|n|om',
    'Molokhia|soep van jutebladeren met kip|l|u',
    'Mahshi|groenten gevuld met rijst|g|u',
    'Fattah|rijst en brood met vlees en knoflooksaus|l|u',
    'Hawawshi|brood gevuld met gekruid gehakt|l|n|ma',
    'Kofta|gehaktspiesjes van de grill|l|n',
    'Shakshuka|eieren in tomatensaus|g|n|om',
    'Om ali|warme broodpudding met noten|g|n|m',
  ],
  ET: [
    'Injera met wat|zuurdesempannenkoek met stoofpotjes|l|u',
    'Doro wat|pittige kipstoof met ei|l|u',
    'Tibs|gebakken stukjes vlees met ui|l|n',
    'Shiro|stoof van kikkererwtenmeel|g|n',
    'Misir wat|pittige stoof van rode linzen|g|n',
    'Kitfo|fijngehakt rundvlees met kruidenboter|l|s',
    'Gomen|gestoofde boerenkool|g|n',
    'Firfir|stukjes injera in pittige saus|g|s|o',
    'Atkilt wat|kool, wortel en aardappel met kurkuma|g|n',
    'Sambusa|gefrituurd deegpakketje met linzen|g|u|m',
  ],
  ZA: [
    'Bobotie|gekruid gehakt uit de oven met ei|l|u',
    'Braai|vlees van de barbecue|l|u',
    'Bunny chow|uitgehold brood gevuld met curry|l|u',
    'Boerewors|gekruide worst van de grill|l|n',
    'Potjiekos|stoofpot uit een gietijzeren pot|l|u',
    'Pap en vleis|maïspap met vlees en saus|l|n',
    'Chakalaka|pittige groentestoof met bonen|g|n',
    'Sosaties|gemarineerde vleesspiesjes|l|u',
    'Tamatiebredie|lamsstoof met tomaat|l|u',
    'Malvapudding|warme zoete pudding|g|u|m',
  ],
  US: [
    'Hamburger|broodje met een burger van rundvlees|l|n',
    'Mac and cheese|macaroni in kaassaus|g|n',
    'Barbecue ribs|varkensribben met barbecuesaus|l|u',
    'Buffalo wings|pittige kippenvleugels|l|u',
    'Clam chowder|romige soep met schelpdieren|v|u|ma',
    'Hotdog|broodje worst met saus|l|s|m',
    'Pancakes met ahornsiroop|dikke luchtige pannenkoeken|g|n|o',
    'Fried chicken|krokant gefrituurde kip|l|u',
    'Caesarsalade|sla met kip, croutons en dressing|l|s|ma',
    'Jambalaya|rijst met worst, kip en garnalen|l|u',
  ],
  MX: [
    'Taco\'s|kleine tortilla\'s met vlees en salsa|l|n',
    'Enchiladas|gevulde tortilla\'s met saus uit de oven|l|u',
    'Guacamole met tortillachips|dip van avocado|g|s|m',
    'Quesadilla|tortilla met gesmolten kaas|g|s|ma',
    'Pozole|soep van maïs en varkensvlees|l|u',
    'Burrito|grote tortilla met rijst, bonen en vlees|l|n',
    'Mole poblano|kip in saus van chili en chocolade|l|u',
    'Tamales|gestoomd maïsdeeg met vulling|l|u',
    'Huevos rancheros|gebakken eieren op tortilla met salsa|g|s|o',
    'Sopa de tortilla|tomatensoep met reepjes tortilla|l|n|ma',
  ],
  SR: [
    'Roti|platbrood met kip, aardappel en kousenband|l|u',
    'Pom|ovenschotel van pomtajer en kip|l|u',
    'Moksi alesi|gemengde rijst met vlees of vis|l|u',
    'Saoto soep|kippensoep met taugé en ei|l|u|ma',
    'Surinaamse nasi met kip|gebakken rijst met kip|l|u',
    'Surinaamse bami|gebakken noedels met kip|l|n',
    'Bruine bonen met rijst|bruine bonen met zoutvlees|l|u',
    'Bara|gefrituurd broodje van linzenmeel|g|u|m',
    'Pindasoep|soep van pindakaas met kip|l|u',
    'Her\'heri|gekookte knollen en banaan met bakkeljauw|v|u',
  ],
  BR: [
    'Feijoada|stoofpot van zwarte bonen en vlees|l|u',
    'Churrasco|vlees van de grill|l|u',
    'Moqueca|visstoof met kokosmelk|v|n',
    'Pão de queijo|kaasbroodjes van tapiocameel|g|n|om',
    'Coxinha|gefrituurde kroket met kip|l|u|m',
    'Feijão tropeiro|bonen met worst en cassavemeel|l|n',
    'Bobó de camarão|garnalen in cassavepuree|v|u',
    'Acarajé|gefrituurd bonenbroodje met garnalen|v|u|m',
    'Arroz com feijão|rijst met bonen|g|n',
    'Picanha|staartstuk van de grill|l|n',
  ],
  AR: [
    'Asado|vlees van de houtskoolgrill|l|u',
    'Empanadas|deegflapjes gevuld met vlees|l|u|ma',
    'Milanesa|gepaneerde lap vlees|l|n',
    'Choripán|broodje chorizo met chimichurri|l|s|m',
    'Locro|stevige soep van maïs en vlees|l|u',
    'Provoleta|gegrilde provolonekaas|g|s|m',
    'Bife de chorizo|entrecote van de grill|l|n',
    'Humita|maïspuree gestoomd in maïsblad|g|u',
    'Carbonada|stoofpot met vlees, pompoen en maïs|l|u',
    'Ñoquis|gnocchi met tomatensaus|g|n',
  ],
  PE: [
    'Ceviche|rauwe vis gemarineerd in limoensap|v|n',
    'Lomo saltado|roerbak van rundvlees met friet|l|n',
    'Ají de gallina|kip in romige pepersaus|l|u',
    'Anticuchos|gegrilde vleesspiesjes|l|n',
    'Causa|aardappeltaartje met tonijn|v|n|m',
    'Papa a la huancaína|aardappels met pittige kaassaus|g|n|m',
    'Arroz con pollo|rijst met kip en koriander|l|u',
    'Rocoto relleno|gevulde pittige paprika|l|u',
    'Pollo a la brasa|kip van het spit|l|u',
    'Tacu tacu|gebakken koek van rijst en bonen|g|n',
  ],
  AU: [
    'Meat pie|pasteitje met rundvlees en jus|l|u|ma',
    'Barramundi|gegrilde witvis|v|n',
    'Chicken parmigiana|gepaneerde kip met tomatensaus en kaas|l|n',
    'Sausage sizzle|worstje op brood met ui|l|s|m',
    'Fish and chips|gefrituurde vis met dikke frieten|v|n',
    'Lamsbout uit de oven|gebraden lamsvlees met groenten|l|u',
    'Vegemite op toast|toast met hartige gistpasta|g|s|o',
    'Pavlova|schuimtaart met room en fruit|g|u|m',
    'Kangoeroesteak|mager vlees van de grill|l|s',
    'Damper|brood gebakken in de hete as|g|u|m',
  ],
});
