'use strict';

// Gerechten per land voor de wereldkeuken, op landcode.
// Een gerecht is 'naam|omschrijving|soort|tijd|maaltijden', met soort l (vlees), v (vis) of g (vegetarisch),
// tijd s (snel), n (gemiddeld) of u (uitgebreid) en maaltijden o, m en a (weggelaten betekent avondeten).
// De gerechten per land zijn een eigen keuze van bekende gerechten, geen officiele ranglijst.
Object.assign(WORLD_DISHES, {
  NL: [
    'Stamppot boerenkool|aardappelpuree met boerenkool en rookworst|l|n',
    'Erwtensoep|dikke soep van spliterwten met rookworst|l|u|ma',
    'Hutspot|stamppot van aardappel, wortel en ui|l|n',
    'Pannenkoeken|grote dunne pannenkoeken, zoet of hartig|g|n|ma',
    'Kibbeling|gefrituurde stukjes witvis met saus|v|s|ma',
    'Hollandse nieuwe|rauwe haring met uitjes|v|s|m',
    'Bitterballen|krokante ragoutballetjes met mosterd|l|s|m',
    'Poffertjes|kleine luchtige pannenkoekjes met poedersuiker|g|n|m',
    'Hachee|stoofvlees met veel ui en laurier|l|u',
    'Broodje kroket|zacht broodje met een rundvleeskroket|l|s|m',
  ],
  BE: [
    'Stoofvlees met friet|rundvlees gestoofd in bier, met frieten|l|u',
    'Mosselen met friet|gekookte mosselen met frieten|v|n',
    'Waterzooi|romige stoofpot met kip en groenten|l|u',
    'Witlof met ham en kaas|witlof in ham gerold, met kaassaus uit de oven|l|u',
    'Vol-au-vent|bladerdeegbakje met kipragout|l|u',
    'Konijn met pruimen|konijn gestoofd met pruimen|l|u',
    'Tomaat-garnaal|tomaat gevuld met grijze garnalen|v|s|m',
    'Balletjes in tomatensaus|gehaktballetjes in tomatensaus|l|n',
    'Stoemp met worst|aardappelpuree met groenten en braadworst|l|n',
    'Luikse wafels|zoete wafels met parelsuiker|g|n|om',
  ],
  FR: [
    'Coq au vin|kip gestoofd in rode wijn|l|u',
    'Boeuf bourguignon|rundvlees gestoofd in rode wijn|l|u',
    'Ratatouille|gestoofde groenten uit de Provence|g|n',
    'Quiche lorraine|hartige taart met spek en ei|l|u|ma',
    'Croque-monsieur|tosti met ham, kaas en bechamelsaus|l|s|m',
    'Bouillabaisse|vissoep uit Marseille|v|u',
    'Cassoulet|stoofpot van witte bonen, worst en eend|l|u',
    'Crêpes|dunne pannenkoeken, zoet of hartig|g|n|om',
    'Franse uiensoep|soep van gekarameliseerde ui met kaasbroodje|l|u|ma',
    'Tartiflette|aardappelgratin met spek en kaas|l|u',
  ],
  IT: [
    'Pizza margherita|pizza met tomaat, mozzarella en basilicum|g|n',
    'Spaghetti carbonara|pasta met ei, spek en pecorino|l|s',
    'Lasagne|laagjes pasta met gehaktsaus en bechamel|l|u',
    'Risotto met paddenstoelen|romige rijst met paddenstoelen|g|n',
    'Spaghetti bolognese|pasta met saus van gehakt en tomaat|l|n',
    'Gnocchi|aardappelknoedels met saus|g|n',
    'Ossobuco|kalfsschenkel gestoofd met groenten|l|u',
    'Minestrone|stevige groentesoep met pasta|g|n|ma',
    'Parmigiana di melanzane|ovenschotel van aubergine, tomaat en kaas|g|u',
    'Saltimbocca|kalfsvlees met ham en salie|l|s',
  ],
  ES: [
    'Paella|rijst met saffraan, kip en zeevruchten|v|u',
    'Tortilla española|dikke omelet met aardappel en ui|g|n|ma',
    'Gazpacho|koude soep van tomaat en groenten|g|s|m',
    'Patatas bravas|gebakken aardappels met pittige saus|g|n|m',
    'Gambas al ajillo|garnalen in knoflookolie|v|s',
    'Pulpo a la gallega|octopus met paprikapoeder en aardappel|v|u',
    'Albondigas|gehaktballetjes in tomatensaus|l|n',
    'Fabada asturiana|stoofpot van witte bonen en worst|l|u',
    'Croquetas|kroketjes met ham|l|n|m',
    'Pisto|gestoofde groenten met een ei|g|n',
  ],
  PT: [
    'Bacalhau à brás|kabeljauw met aardappel en ei|v|n',
    'Caldo verde|soep van aardappel, kool en chorizo|l|n|ma',
    'Francesinha|sandwich met vlees, kaas en biersaus|l|n',
    'Sardinhas assadas|gegrilde sardines|v|s',
    'Arroz de marisco|rijst met zeevruchten|v|u',
    'Cozido à portuguesa|stoofpot van vlees, worst en groenten|l|u',
    'Frango piri-piri|gegrilde kip met pittige saus|l|u',
    'Bifana|broodje met gemarineerd varkensvlees|l|s|m',
    'Polvo à lagareiro|octopus uit de oven met aardappel|v|u',
    'Pastel de nata|bladerdeegtaartje met custard|g|u|om',
  ],
  DE: [
    'Schnitzel|gepaneerde lap kalfs- of varkensvlees|l|n',
    'Bratwurst met zuurkool|braadworst met zuurkool en mosterd|l|n',
    'Sauerbraten|gemarineerd rundvlees, lang gestoofd|l|u',
    'Käsespätzle|eiernoedels met kaas en gebakken ui|g|n',
    'Currywurst|worst met curryketchup en friet|l|s|ma',
    'Kartoffelsalat|aardappelsalade met spek|l|n|ma',
    'Rouladen|rundvleesrolletjes met spek en augurk|l|u',
    'Maultaschen|gevulde deegkussentjes|l|n',
    'Eisbein|gekookte varkensschenkel met zuurkool|l|u',
    'Flammkuchen|dunne bodem met zure room, ui en spek|l|n',
  ],
  GB: [
    'Fish and chips|gefrituurde vis met dikke frieten|v|n',
    'Full English breakfast|eieren, spek, worst, bonen en toast|l|n|o',
    'Shepherd\'s pie|lamsgehakt met een laag aardappelpuree|l|u',
    'Sunday roast|gebraden vlees met groenten en jus|l|u',
    'Chicken tikka masala|kip in romige tomaten-kerriesaus|l|n',
    'Bangers and mash|worstjes met aardappelpuree en uienjus|l|n',
    'Beef Wellington|ossenhaas in bladerdeeg|l|u',
    'Cornish pasty|deegflap gevuld met vlees en groenten|l|u|ma',
    'Toad in the hole|worstjes in gebakken beslag|l|u',
    'Scones met jam|luchtige broodjes met room en jam|g|n|om',
  ],
  GR: [
    'Moussaka|ovenschotel met aubergine en gehakt|l|u',
    'Souvlaki|vleesspiesjes met pitabrood|l|n',
    'Gyros|geroosterd vlees in pitabrood|l|s|ma',
    'Griekse salade|tomaat, komkommer, olijven en feta|g|s|ma',
    'Spanakopita|bladerdeegtaart met spinazie en feta|g|u|ma',
    'Pastitsio|pastaschotel met gehakt en bechamel|l|u',
    'Dolmades|wijnbladeren gevuld met rijst|g|u|m',
    'Gemista|tomaten en paprika gevuld met rijst|g|u',
    'Stifado|rundvlees gestoofd met zilveruitjes|l|u',
    'Tzatziki met brood|yoghurtdip met komkommer en knoflook|g|s|m',
  ],
  TR: [
    'Döner kebab|geroosterd vlees van het spit|l|s|ma',
    'Lahmacun|dunne Turkse pizza met gehakt|l|n|ma',
    'Köfte|gekruide gehaktballetjes van de grill|l|n',
    'İskender kebab|döner op brood met tomatensaus en yoghurt|l|n',
    'Menemen|roerei met tomaat en paprika|g|s|o',
    'Mantı|kleine gevulde deegkussentjes met yoghurt|l|u',
    'Pide|bootvormig brood met vulling|l|n',
    'İmam bayıldı|gevulde aubergine met ui en tomaat|g|u',
    'Mercimek çorbası|soep van rode linzen|g|n|ma',
    'Börek|bladerdeeg met kaas en spinazie|g|u|om',
  ],
  LB: [
    'Falafel|gefrituurde balletjes van kikkererwten|g|n|ma',
    'Hummus|puree van kikkererwten en tahin|g|s|m',
    'Tabouleh|salade van peterselie, bulgur en tomaat|g|s|m',
    'Shoarma|gekruid vlees in pitabrood|l|n|ma',
    'Kibbeh|gehakt met bulgur, gefrituurd|l|u',
    'Fattoush|salade met gebakken pitabrood|g|s|m',
    'Manakish|plat brood met za\'atar of kaas|g|n|om',
    'Baba ganoush|puree van geroosterde aubergine|g|n|m',
    'Kafta|gekruide gehaktspiesjes|l|n',
    'Mujaddara|linzen met rijst en gebakken ui|g|n',
  ],
  IN: [
    'Butter chicken|kip in romige tomatensaus|l|u',
    'Biryani|gekruide rijst met vlees|l|u',
    'Dal|gekruide stoof van linzen|g|n',
    'Palak paneer|spinaziecurry met verse kaas|g|n',
    'Tandoori chicken|gemarineerde kip uit de oven|l|u',
    'Chana masala|curry van kikkererwten|g|n',
    'Samosa|gefrituurd deegpakketje met aardappel|g|u|m',
    'Masala dosa|krokante pannenkoek met aardappelvulling|g|u|om',
    'Rogan josh|lamscurry uit Kasjmir|l|u',
    'Aloo gobi|curry van aardappel en bloemkool|g|n',
  ],
  CN: [
    'Pekingeend|geroosterde eend met pannenkoekjes|l|u',
    'Dumplings|gestoomde of gebakken deegpakketjes|l|u|ma',
    'Kung pao kip|roerbak van kip, pinda\'s en chilipeper|l|s',
    'Mapo tofu|tofu in pittige saus met gehakt|l|n',
    'Zoetzuur varkensvlees|krokant varkensvlees in zoetzure saus|l|n',
    'Gebakken rijst|rijst uit de wok met ei en groenten|g|s',
    'Chow mein|gebakken noedels met groenten|g|s',
    'Hot pot|samen koken in een pan bouillon|l|u',
    'Loempia\'s|gefrituurde rolletjes met groenten|g|u|m',
    'Wontonsoep|bouillon met gevulde deegkussentjes|l|n|ma',
  ],
  JP: [
    'Sushi|rijst met rauwe vis of groenten|v|u',
    'Ramen|noedelsoep met bouillon en toppings|l|u',
    'Tempura|garnalen en groenten in luchtig beslag|v|n',
    'Tonkatsu|gepaneerde varkenskotelet|l|n',
    'Okonomiyaki|hartige pannenkoek met kool|l|n',
    'Yakitori|kipspiesjes van de grill|l|n',
    'Udon|dikke noedels in bouillon|v|n',
    'Japanse curry|milde curry met rijst|l|n',
    'Gyoza|gebakken dumplings|l|u|ma',
    'Misosoep|soep van misopasta met tofu|v|s|om',
  ],
  KR: [
    'Bibimbap|rijst met groenten, ei en chilipasta|g|n',
    'Bulgogi|gemarineerd rundvlees van de grill|l|n',
    'Kimchi jjigae|stoofpot van kimchi met tofu|l|n',
    'Koreaanse gefrituurde kip|krokante kip met zoet-pittige saus|l|u',
    'Japchae|glasnoedels met groenten|g|n',
    'Tteokbokki|rijstcakes in pittige saus|v|s|ma',
    'Kimbap|rijstrollen met groenten in zeewier|g|n|m',
    'Samgyeopsal|gegrild buikspek met sla|l|n',
    'Sundubu jjigae|pittige soep met zachte tofu|v|n',
    'Pajeon|hartige pannenkoek met lente-ui|g|s|ma',
  ],
  TH: [
    'Pad thai|gebakken rijstnoedels met ei en pinda\'s|l|s',
    'Groene curry|curry met kokosmelk en kip|l|n',
    'Tom yum|pittig-zure soep met garnalen|v|n',
    'Massaman curry|milde curry met aardappel en pinda\'s|l|u',
    'Som tam|pittige salade van groene papaja|v|s|m',
    'Pad kra pao|roerbak met basilicum en gehakt|l|s',
    'Tom kha gai|kokossoep met kip|l|n',
    'Khao pad|Thaise gebakken rijst|l|s',
    'Rode curry|pittige curry met kokosmelk|l|n',
    'Mango met kleefrijst|zoete rijst met mango|g|n|m',
  ],
  VN: [
    'Pho|noedelsoep met rundvlees en kruiden|l|u',
    'Banh mi|stokbrood met vlees en ingelegde groenten|l|s|m',
    'Verse loempia\'s|rijstvelrolletjes met garnalen en kruiden|v|n|m',
    'Bun cha|gegrild varkensvlees met noedels|l|n',
    'Com tam|gebroken rijst met gegrild vlees|l|n',
    'Bun bo Hue|pittige noedelsoep met rundvlees|l|u',
    'Banh xeo|krokante pannenkoek met garnalen|v|n',
    'Cha gio|gefrituurde loempia\'s|l|u|m',
    'Ca kho to|vis gestoofd in karamelsaus|v|u',
    'Goi ga|frisse salade met kip en kruiden|l|s|m',
  ],
  ID: [
    'Nasi goreng|gebakken rijst met ketjap en ei|l|n',
    'Saté|vleesspiesjes met pindasaus|l|n',
    'Rendang|rundvlees lang gestoofd in kokos en kruiden|l|u',
    'Gado gado|groenten met pindasaus|g|n',
    'Bami goreng|gebakken noedels met groenten|l|n',
    'Soto ayam|kippensoep met kurkuma|l|u|ma',
    'Bakso|soep met gehaktballetjes|l|n|ma',
    'Ayam goreng|gefrituurde gemarineerde kip|l|u',
    'Sambal goreng boontjes|pittige roergebakken boontjes|v|s',
    'Tempeh goreng|gebakken tempeh|g|s',
  ],
  MA: [
    'Tajine met kip|kip gestoofd met citroen en olijven|l|u',
    'Couscous|couscous met groenten en vlees|l|u',
    'Harira|soep van tomaat, linzen en kikkererwten|l|u|ma',
    'Pastilla|hartig-zoete taart met kip en amandel|l|u',
    'Kefta tajine|gehaktballetjes in tomatensaus met ei|l|n',
    'Zaalouk|salade van gestoofde aubergine|g|n|m',
    'Mechoui|langzaam geroosterd lamsvlees|l|u',
    'Bissara|soep van gedroogde tuinbonen|g|u|om',
    'Msemen|gevouwen pannenkoeken|g|u|o',
    'Sardines met chermoula|sardines met kruidenmarinade|v|n',
  ],
  EG: [
    'Koshari|rijst, linzen en pasta met tomatensaus|g|u',
    'Ful medames|gestoofde tuinbonen|g|u|o',
    'Ta\'ameya|falafel van tuinbonen|g|n|om',
    'Molokhia|soep van jutebladeren met kip|l|u',
    'Mahshi|groenten gevuld met rijst|g|u',
    'Fattah|rijst en brood met vlees en knoflooksaus|l|u',
    'Hawawshi|brood gevuld met gekruid gehakt|l|n|ma',
    'Kofta|gehaktspiesjes van de grill|l|n',
    'Shakshuka|eieren in tomatensaus|g|n|om',
    'Om ali|warme broodpudding met noten|g|n|m',
  ],
  ET: [
    'Injera met wat|zuurdesempannenkoek met stoofpotjes|l|u',
    'Doro wat|pittige kipstoof met ei|l|u',
    'Tibs|gebakken stukjes vlees met ui|l|n',
    'Shiro|stoof van kikkererwtenmeel|g|n',
    'Misir wat|pittige stoof van rode linzen|g|n',
    'Kitfo|fijngehakt rundvlees met kruidenboter|l|s',
    'Gomen|gestoofde boerenkool|g|n',
    'Firfir|stukjes injera in pittige saus|g|s|o',
    'Atkilt wat|kool, wortel en aardappel met kurkuma|g|n',
    'Sambusa|gefrituurd deegpakketje met linzen|g|u|m',
  ],
  ZA: [
    'Bobotie|gekruid gehakt uit de oven met ei|l|u',
    'Braai|vlees van de barbecue|l|u',
    'Bunny chow|uitgehold brood gevuld met curry|l|u',
    'Boerewors|gekruide worst van de grill|l|n',
    'Potjiekos|stoofpot uit een gietijzeren pot|l|u',
    'Pap en vleis|maïspap met vlees en saus|l|n',
    'Chakalaka|pittige groentestoof met bonen|g|n',
    'Sosaties|gemarineerde vleesspiesjes|l|u',
    'Tamatiebredie|lamsstoof met tomaat|l|u',
    'Malvapudding|warme zoete pudding|g|u|m',
  ],
  US: [
    'Hamburger|broodje met een burger van rundvlees|l|n',
    'Mac and cheese|macaroni in kaassaus|g|n',
    'Barbecue ribs|varkensribben met barbecuesaus|l|u',
    'Buffalo wings|pittige kippenvleugels|l|u',
    'Clam chowder|romige soep met schelpdieren|v|u|ma',
    'Hotdog|broodje worst met saus|l|s|m',
    'Pancakes met ahornsiroop|dikke luchtige pannenkoeken|g|n|o',
    'Fried chicken|krokant gefrituurde kip|l|u',
    'Caesarsalade|sla met kip, croutons en dressing|l|s|ma',
    'Jambalaya|rijst met worst, kip en garnalen|l|u',
  ],
  MX: [
    'Taco\'s|kleine tortilla\'s met vlees en salsa|l|n',
    'Enchiladas|gevulde tortilla\'s met saus uit de oven|l|u',
    'Guacamole met tortillachips|dip van avocado|g|s|m',
    'Quesadilla|tortilla met gesmolten kaas|g|s|ma',
    'Pozole|soep van maïs en varkensvlees|l|u',
    'Burrito|grote tortilla met rijst, bonen en vlees|l|n',
    'Mole poblano|kip in saus van chili en chocolade|l|u',
    'Tamales|gestoomd maïsdeeg met vulling|l|u',
    'Huevos rancheros|gebakken eieren op tortilla met salsa|g|s|o',
    'Sopa de tortilla|tomatensoep met reepjes tortilla|l|n|ma',
  ],
  SR: [
    'Roti|platbrood met kip, aardappel en kousenband|l|u',
    'Pom|ovenschotel van pomtajer en kip|l|u',
    'Moksi alesi|gemengde rijst met vlees of vis|l|u',
    'Saoto soep|kippensoep met taugé en ei|l|u|ma',
    'Surinaamse nasi met kip|gebakken rijst met kip|l|u',
    'Surinaamse bami|gebakken noedels met kip|l|n',
    'Bruine bonen met rijst|bruine bonen met zoutvlees|l|u',
    'Bara|gefrituurd broodje van linzenmeel|g|u|m',
    'Pindasoep|soep van pindakaas met kip|l|u',
    'Her\'heri|gekookte knollen en banaan met bakkeljauw|v|u',
  ],
  BR: [
    'Feijoada|stoofpot van zwarte bonen en vlees|l|u',
    'Churrasco|vlees van de grill|l|u',
    'Moqueca|visstoof met kokosmelk|v|n',
    'Pão de queijo|kaasbroodjes van tapiocameel|g|n|om',
    'Coxinha|gefrituurde kroket met kip|l|u|m',
    'Feijão tropeiro|bonen met worst en cassavemeel|l|n',
    'Bobó de camarão|garnalen in cassavepuree|v|u',
    'Acarajé|gefrituurd bonenbroodje met garnalen|v|u|m',
    'Arroz com feijão|rijst met bonen|g|n',
    'Picanha|staartstuk van de grill|l|n',
  ],
  AR: [
    'Asado|vlees van de houtskoolgrill|l|u',
    'Empanadas|deegflapjes gevuld met vlees|l|u|ma',
    'Milanesa|gepaneerde lap vlees|l|n',
    'Choripán|broodje chorizo met chimichurri|l|s|m',
    'Locro|stevige soep van maïs en vlees|l|u',
    'Provoleta|gegrilde provolonekaas|g|s|m',
    'Bife de chorizo|entrecote van de grill|l|n',
    'Humita|maïspuree gestoomd in maïsblad|g|u',
    'Carbonada|stoofpot met vlees, pompoen en maïs|l|u',
    'Ñoquis|gnocchi met tomatensaus|g|n',
  ],
  PE: [
    'Ceviche|rauwe vis gemarineerd in limoensap|v|n',
    'Lomo saltado|roerbak van rundvlees met friet|l|n',
    'Ají de gallina|kip in romige pepersaus|l|u',
    'Anticuchos|gegrilde vleesspiesjes|l|n',
    'Causa|aardappeltaartje met tonijn|v|n|m',
    'Papa a la huancaína|aardappels met pittige kaassaus|g|n|m',
    'Arroz con pollo|rijst met kip en koriander|l|u',
    'Rocoto relleno|gevulde pittige paprika|l|u',
    'Pollo a la brasa|kip van het spit|l|u',
    'Tacu tacu|gebakken koek van rijst en bonen|g|n',
  ],
  AU: [
    'Meat pie|pasteitje met rundvlees en jus|l|u|ma',
    'Barramundi|gegrilde witvis|v|n',
    'Chicken parmigiana|gepaneerde kip met tomatensaus en kaas|l|n',
    'Sausage sizzle|worstje op brood met ui|l|s|m',
    'Fish and chips|gefrituurde vis met dikke frieten|v|n',
    'Lamsbout uit de oven|gebraden lamsvlees met groenten|l|u',
    'Vegemite op toast|toast met hartige gistpasta|g|s|o',
    'Pavlova|schuimtaart met room en fruit|g|u|m',
    'Kangoeroesteak|mager vlees van de grill|l|s',
    'Damper|brood gebakken in de hete as|g|u|m',
  ],
});

// Europa. Van kleine landen staan er minder dan tien gerechten: alleen wat er echt bekend is.
Object.assign(WORLD_DISHES, {
  AL: [
    'Tavë kosi|lamsvlees met rijst uit de oven onder een laag yoghurt|l|u',
    'Byrek|hartige taart van dun deeg met spinazie of kaas|g|u|ma',
    'Fërgesë|stoofschotel van paprika, tomaat en verse kaas|g|n',
    'Qofte|gekruide gehaktballetjes van de grill|l|n',
    'Speca të mbushura|paprika gevuld met rijst en gehakt|l|u',
    'Jani me fasule|soep van witte bonen|g|u|ma',
    'Flija|laagjespannenkoek met room, urenlang gebakken|g|u|m',
    'Tarator|koude soep van yoghurt en komkommer|g|s|m',
    'Petulla|gefrituurde deegballetjes met honing of kaas|g|n|om',
  ],
  AD: [
    'Escudella|stevige stoofpot met vlees, worst, kikkererwten en pasta|l|u',
    'Trinxat|koek van aardappel, kool en spek uit de pan|l|n',
    'Truita de riu|forel uit de bergbeek, gebakken met ham|v|n',
    'Cargols a la llauna|slakken uit de oven met knoflookolie|l|n',
    'Civet de senglar|stoofpot van wild zwijn in rode wijn|l|u',
    'Embotits|bord met gedroogde worsten uit de bergen|l|s|m',
    'Pa amb tomàquet|brood ingewreven met tomaat en olijfolie|g|s|om',
  ],
  AT: [
    'Wiener schnitzel|dunne gepaneerde kalfsschnitzel|l|n',
    'Tafelspitz|gekookt rundvlees met appel-mierikswortelsaus|l|u',
    'Kaiserschmarrn|dikke pannenkoek in stukken met pruimencompote|g|n|ma',
    'Käsespätzle|eiernoedels met gesmolten kaas en gebakken ui|g|n',
    'Backhendl|gepaneerde gefrituurde kip|l|n',
    'Tiroler Gröstl|gebakken aardappel met spek, ui en een spiegelei|l|n',
    'Speckknödel|broodknoedels met spek in bouillon|l|n',
    'Wiener Saftgulasch|rundvleesstoofpot met veel ui en paprikapoeder|l|u',
    'Apfelstrudel|dun deeg gevuld met appel en rozijnen|g|u|m',
    'Sachertorte|chocoladetaart met abrikozenjam|g|u|m',
  ],
  BY: [
    'Draniki|aardappelpannenkoekjes met zure room|g|n|ma',
    'Machanka|varkensvlees in dikke saus, met pannenkoeken|l|u',
    'Kalduny|deegkussentjes gevuld met vlees|l|u',
    'Babka|aardappelschotel met spek uit de oven|l|u',
    'Chaladnik|koude bietensoep met zure room|g|n|m',
    'Kletski|aardappelballen gevuld met vlees|l|u',
    'Borsjtsj|bietensoep met zure room|l|u|ma',
    'Syrniki|kwarkkoekjes uit de pan|g|n|o',
  ],
  BA: [
    'Ćevapi|gegrilde gehaktrolletjes in plat brood met ui|l|n|ma',
    'Burek|opgerold dun deeg gevuld met gehakt|l|u|oma',
    'Bosanski lonac|stoofpot van vlees en groenten|l|u',
    'Begova čorba|romige kippensoep met okra|l|u',
    'Sarma|koolrolletjes gevuld met gehakt en rijst|l|u',
    'Sogan-dolma|uien gevuld met gehakt en rijst|l|u',
    'Klepe|deegkussentjes met gehakt en knoflookyoghurt|l|u',
    'Zeljanica|taart van dun deeg met spinazie en kaas|g|u|ma',
    'Grah|bonensoep met gerookt vlees|l|u',
    'Tufahija|gepocheerde appel gevuld met walnoten|g|u|m',
  ],
  BG: [
    'Banitsa|taart van dun deeg met ei en witte kaas|g|u|om',
    'Shopska-salade|salade van tomaat, komkommer en geraspte witte kaas|g|s|ma',
    'Tarator|koude soep van yoghurt, komkommer en dille|g|s|m',
    'Kebapche|gegrilde gehaktrolletjes|l|n',
    'Kavarma|stoofpot van varkensvlees en groenten uit een aardewerken pot|l|u',
    'Moussaka|ovenschotel van aardappel en gehakt|l|u',
    'Sarmi|kool- of druivenbladeren gevuld met rijst en gehakt|l|u',
    'Bob chorba|bonensoep met munt|g|u|ma',
    'Gyuvech|groenten en vlees uit de oven|l|u',
    'Mekitsi|gefrituurd deeg met jam of witte kaas|g|n|o',
  ],
  HR: [
    'Peka|vlees of inktvis met aardappel, gegaard onder een ijzeren stolp|l|u',
    'Crni rižot|zwarte risotto met inktvis|v|n',
    'Pašticada|rundvlees gestoofd in wijn, met gnocchi|l|u',
    'Štrukli|deeg gevuld met verse kaas, gekookt of gebakken|g|u|ma',
    'Brodet|visstoofpot met polenta|v|u',
    'Sarma|koolrolletjes gevuld met gehakt en rijst|l|u',
    'Zagrebački odrezak|gepaneerde schnitzel gevuld met ham en kaas|l|n',
    'Fuži met truffel|pasta uit Istrië met truffel|g|n',
    'Buzara|garnalen of mosselen in wijn, knoflook en peterselie|v|n',
    'Soparnik|platte taart gevuld met snijbiet|g|u|m',
  ],
  CY: [
    'Halloumi van de grill|gegrilde stevige kaas|g|s|ma',
    'Souvla|grote stukken vlees aan het spit boven houtskool|l|u',
    'Sheftalia|gegrilde worstjes van gehakt|l|n',
    'Kleftiko|lamsvlees, langzaam gegaard in de oven|l|u',
    'Afelia|varkensvlees gestoofd in rode wijn met koriander|l|u',
    'Koupepia|druivenbladeren gevuld met gehakt en rijst|l|u',
    'Makaronia tou fournou|ovenschotel van pasta, gehakt en bechamelsaus|l|u',
    'Stifado|stoofpot van rundvlees met kleine uitjes|l|u',
    'Louvi|ogenboontjes met snijbiet, olijfolie en citroen|g|n',
    'Loukoumades|deegballetjes met honing|g|n|m',
  ],
  CZ: [
    'Svíčková|rundvlees in roomsaus van wortelgroenten, met knoedels|l|u',
    'Vepřo knedlo zelo|varkensgebraad met knoedels en zuurkool|l|u',
    'Guláš|rundvleesgoulash met broodknoedels|l|u',
    'Smažený sýr|gepaneerde gefrituurde kaas met tartaarsaus|g|n',
    'Řízek|gepaneerde schnitzel met aardappelsalade|l|n',
    'Kulajda|romige soep met paddenstoelen, dille en ei|g|n|ma',
    'Bramboráky|aardappelpannenkoekjes met knoflook en marjolein|g|n',
    'Česnečka|knoflooksoep met aardappel en kaas|g|n|ma',
    'Ovocné knedlíky|knoedels gevuld met fruit|g|u',
    'Koláče|ronde zoete broodjes met maanzaad of kwark|g|u|om',
  ],
  DK: [
    'Smørrebrød|roggebrood rijk belegd met haring, garnalen of vlees|v|s|m',
    'Stegt flæsk|krokant gebakken buikspek met peterseliesaus en aardappels|l|n',
    'Frikadeller|platte gehaktballen uit de pan|l|n',
    'Flæskesteg|varkensgebraad met krokant zwoerd|l|u',
    'Rød pølse|rode hotdog van de kraam|l|s|m',
    'Tarteletter|deegbakjes met kip en asperges|l|n',
    'Boller i karry|gehaktballetjes in kerriesaus met rijst|l|n',
    'Hakkebøf|gebakken gehaktbiefstuk met ui|l|n',
    'Æbleskiver|bolle poffers met jam en poedersuiker|g|n|m',
    'Rødgrød med fløde|pudding van rode bessen met room|g|n|m',
  ],
  EE: [
    'Verivorst|bloedworst met vossenbessen|l|n',
    'Mulgipuder|aardappelpuree met gerst en spek|l|u',
    'Mulgikapsad|zuurkool gestoofd met varkensvlees en gerst|l|u',
    'Kiluvõileib|roggebrood met sprot en ei|v|s|m',
    'Sült|vlees in gelei|l|u|m',
    'Rosolje|salade van biet, aardappel en haring|v|n|m',
    'Praetud räimed|gebakken haring uit de Oostzee|v|n',
    'Pirukad|kleine gevulde broodjes met vlees|l|u|m',
    'Kama|meel van geroosterde granen, geroerd door karnemelk|g|s|o',
    'Vastlakukkel|zoet broodje met slagroom|g|u|m',
  ],
  FI: [
    'Karjalanpiirakka|roggepasteitje met rijstepap en eiboter|g|u|om',
    'Lohikeitto|romige zalmsoep met aardappel en dille|v|n|ma',
    'Karjalanpaisti|stoofpot van rund- en varkensvlees|l|u',
    'Poronkäristys|gebakken rendiervlees met aardappelpuree en vossenbessen|l|n',
    'Kalakukko|roggebrood gevuld met vis en spek|v|u',
    'Lihapullat|gehaktballetjes met jus|l|n',
    'Hernekeitto|erwtensoep met ham|l|u|ma',
    'Makaronilaatikko|ovenschotel van macaroni en gehakt|l|u',
    'Korvapuusti|kaneelbroodje|g|u|m',
    'Mustikkapiirakka|bosbessentaart|g|u|m',
  ],
  HU: [
    'Gulyás|soep van rundvlees, aardappel en paprikapoeder|l|u',
    'Pörkölt|vleesstoofpot met paprikapoeder|l|u',
    'Paprikás csirke|kip in romige paprikasaus met deegballetjes|l|u',
    'Lángos|gefrituurd plat brood met zure room en kaas|g|n|m',
    'Halászlé|pittige vissoep met karper|v|u',
    'Töltött káposzta|koolrolletjes gevuld met gehakt|l|u',
    'Lecsó|stoofschotel van paprika, tomaat en ui|g|n',
    'Hortobágyi palacsinta|pannenkoek gevuld met vleesragout|l|u',
    'Rakott krumpli|ovenschotel van aardappel, ei en worst|l|u',
    'Dobostorta|laagjestaart met chocoladecrème en karamel|g|u|m',
  ],
  IS: [
    'Plokkfiskur|stamppot van vis en aardappel|v|n',
    'Kjötsúpa|lamssoep met wortelgroenten|l|u',
    'Hangikjöt|gerookt lamsvlees met aardappel in witte saus|l|u',
    'Pylsa|hotdog met lamsvlees en gefrituurde ui|l|s|m',
    'Harðfiskur|gedroogde vis met boter|v|s|m',
    'Humarsúpa|romige soep van langoustine|v|n',
    'Skyr|dikke zuivel, vaak met bessen|g|s|om',
    'Rúgbrauð|donker zoet roggebrood, gebakken in hete aarde|g|u|om',
    'Hákarl|gefermenteerde haai, een beruchte specialiteit|v|s|m',
    'Kleinur|gedraaide gefrituurde koekjes|g|n|m',
  ],
  IE: [
    'Irish stew|stoofpot van lamsvlees, aardappel en ui|l|u',
    'Colcannon|aardappelpuree met kool|g|n',
    'Boxty|aardappelpannenkoek|g|n|oma',
    'Full Irish breakfast|ontbijt met spek, worst, ei en bloedworst|l|n|o',
    'Soda bread|brood met zuiveringszout in plaats van gist|g|u|om',
    'Coddle|stoofpot van worst, spek en aardappel uit Dublin|l|u',
    'Bacon and cabbage|gekookt spek met kool en aardappels|l|u',
    'Seafood chowder|romige soep met vis en schelpdieren|v|n|ma',
    'Shepherd\'s pie|lamsgehakt onder aardappelpuree uit de oven|l|u',
    'Beef and Guinness stew|rundvlees gestoofd in donker bier|l|u',
  ],
  LV: [
    'Pelēkie zirņi ar speķi|grauwe erwten met spek|l|u',
    'Rupjmaize|donker roggebrood|g|u|om',
    'Sklandrausis|roggetaartje met aardappel en wortel|g|u|m',
    'Aukstā zupa|koude bietensoep|g|n|m',
    'Karbonāde|gepaneerde varkenslap|l|n',
    'Frikadeļu zupa|soep met gehaktballetjes|l|n|ma',
    'Kartupeļu pankūkas|aardappelpannenkoekjes|g|n',
    'Speķa pīrāgi|broodjes gevuld met spek|l|u|m',
    'Rasols|salade van aardappel, ei en vlees|l|n|m',
    'Maizes zupa|zoete soep van roggebrood met slagroom|g|n|m',
  ],
  LI: [
    'Käsknöpfle|deegdruppels met gesmolten kaas en gebakken ui|g|n',
    'Ribel|gebakken maisgriesmeel, bij koffie of appelmoes|g|n|o',
    'Hafalaab|soep met maisknoedels en ham|l|u',
    'Rösti|gebakken koek van geraspte aardappel|g|n',
  ],
  LT: [
    'Cepelinai|grote aardappelknoedels gevuld met gehakt, met speksaus|l|u',
    'Šaltibarščiai|koude roze bietensoep met kefir|g|n|m',
    'Kugelis|aardappelschotel met spek uit de oven|l|u',
    'Kibinai|pasteitjes gevuld met lamsvlees|l|u|m',
    'Bulviniai blynai|aardappelpannenkoekjes|g|n',
    'Balandėliai|koolrolletjes gevuld met gehakt|l|u',
    'Koldūnai|deegkussentjes met vlees|l|n',
    'Vėdarai|worst van aardappel|l|u',
    'Kepta duona|gefrituurd roggebrood met knoflook en kaas|g|s|m',
    'Šakotis|boomtaart van het spit|g|u|m',
  ],
  LU: [
    'Judd mat Gaardebounen|gerookte varkensnek met tuinbonen|l|u',
    'Bouneschlupp|soep van sperziebonen, aardappel en spek|l|n|ma',
    'Gromperekichelcher|aardappelkoekjes met ui en peterselie|g|n|m',
    'Kniddelen|meelknoedels met spek|l|n',
    'Forel in riesling|forel in een saus van witte wijn en room|v|n',
    'Rieslingspaschtéit|pasteitje met vlees en gelei van witte wijn|l|u|m',
    'Kachkéis|gesmolten smeerkaas op brood|g|s|m',
    'Träipen|bloedworst met appelmoes|l|n',
    'Wäinzoossiss|worst in een saus van wijn en mosterd|l|n',
    'Quetschentaart|pruimentaart|g|u|m',
  ],
  MT: [
    'Stuffat tal-fenek|konijnenstoofpot met wijn en knoflook|l|u',
    'Pastizzi|deeghapjes met ricotta of erwtenpuree|g|u|om',
    'Ftira|rond brood belegd met tonijn, tomaat en kappertjes|v|s|m',
    'Lampuki pie|vispastei met goudmakreel|v|u',
    'Aljotta|vissoep met knoflook en rijst|v|n',
    'Timpana|macaroni-ovenschotel in deeg|l|u',
    'Bragioli|rolletjes rundvlees, gestoofd in saus|l|u',
    'Ħobż biż-żejt|brood met tomatenpuree, olijfolie en tonijn|v|s|m',
    'Kapunata|gestoofde aubergine, paprika en tomaat|g|n',
    'Imqaret|gefrituurde dadelkoekjes|g|n|m',
  ],
  MD: [
    'Mămăligă|maispap met kaas en zure room|g|n',
    'Sarmale|kool- of druivenbladeren gevuld met rijst en vlees|l|u',
    'Plăcinte|platte gevulde broden met kaas, aardappel of kool|g|u|ma',
    'Zeamă|kippensoep met zelfgemaakte noedels|l|u|ma',
    'Mititei|gegrilde gehaktrolletjes|l|n',
    'Tocană|stoofpot van varkensvlees|l|u',
    'Ardei umpluți|paprika gevuld met rijst en gehakt|l|u',
    'Cozonac|zoet feestbrood met noten|g|u|m',
  ],
  MC: [
    'Barbajuan|gefrituurde deegkussentjes met snijbiet en ricotta|g|u|m',
    'Stocafi|stokvis gestoofd in tomatensaus|v|u',
    'Socca|pannenkoek van kikkererwtenmeel|g|n|m',
    'Pissaladière|uientaart met ansjovis en olijven|v|u|m',
    'Fougasse monégasque|zoet plat brood met anijs en noten|g|u|m',
  ],
  ME: [
    'Njeguški pršut|gerookte gedroogde ham uit de bergen|l|s|m',
    'Kačamak|pap van mais en aardappel met kaas en room|g|n',
    'Cicvara|maispap met jonge kaas|g|n|o',
    'Ispod sača|vlees met aardappel onder een ijzeren stolp|l|u',
    'Crni rižot|zwarte risotto met inktvis|v|n',
    'Buzara|garnalen of mosselen in wijn en knoflook|v|n',
    'Raštan|stoofpot van kool met gerookt vlees|l|u',
    'Jagnjetina u mlijeku|lamsvlees gekookt in melk|l|u',
    'Priganice|gefrituurde deegballetjes met honing en kaas|g|n|o',
  ],
  MK: [
    'Tavče gravče|witte bonen uit de oven in een aardewerken schaal|g|u',
    'Ajvar|smeersel van geroosterde paprika|g|u|m',
    'Pastrmajlija|ovaal brood met gezouten vlees en ei|l|u',
    'Turli tava|groenten en vlees uit de oven|l|u',
    'Šopska-salade|salade van tomaat, komkommer en witte kaas|g|s|ma',
    'Selsko meso|varkensvlees met paddenstoelen uit een aardewerken pot|l|u',
    'Burek|opgerold dun deeg gevuld met gehakt of kaas|l|u|om',
    'Sarma|koolrolletjes gevuld met gehakt en rijst|l|u',
    'Zelnik|taart van dun deeg met prei of spinazie|g|u|m',
    'Kebapi|gegrilde gehaktrolletjes|l|n',
  ],
  NO: [
    'Fårikål|lamsvlees gestoofd met kool en peperkorrels|l|u',
    'Kjøttkaker|gehaktballen in bruine saus|l|n',
    'Raspeballer|aardappelknoedels met gezouten vlees|l|u',
    'Lutefisk|gedroogde vis, geweekt en gekookt, met spek en erwtenpuree|v|u',
    'Pinnekjøtt|gezouten lamsribben, gestoomd|l|u',
    'Gravlaks|gepekelde zalm met mosterd-dillesaus|v|s|m',
    'Lapskaus|stoofpot van vlees en aardappel|l|u',
    'Fiskesuppe|romige vissoep|v|n',
    'Brunost|bruine karamelkaas op brood of wafels|g|s|om',
    'Vafler|hartvormige wafels met jam en zure room|g|n|m',
  ],
  PL: [
    'Pierogi|deegkussentjes met aardappel en kwark, vlees of kool|g|u',
    'Bigos|stoofpot van zuurkool, kool en vlees|l|u',
    'Żurek|zure roggesoep met worst en ei|l|n|ma',
    'Kotlet schabowy|gepaneerde varkenskotelet|l|n',
    'Gołąbki|koolrolletjes met gehakt en rijst in tomatensaus|l|u',
    'Barszcz|heldere bietensoep|g|n|ma',
    'Placki ziemniaczane|aardappelpannenkoekjes|g|n',
    'Rosół|heldere kippenbouillon met noedels|l|u|ma',
    'Zapiekanka|half stokbrood met champignons en kaas uit de oven|g|s|m',
    'Sernik|kwarktaart|g|u|m',
  ],
  RO: [
    'Sarmale|koolrolletjes met gehakt en rijst|l|u',
    'Mămăligă|maispap met kaas en zure room|g|n',
    'Mici|gegrilde gehaktrolletjes met mosterd|l|n',
    'Ciorbă de perișoare|zure soep met gehaktballetjes|l|u|ma',
    'Ciorbă de burtă|zure soep van pens|l|u',
    'Tochitură|stoofpot van varkensvlees met maispap en ei|l|u',
    'Fasole cu cârnați|bonen met worst|l|u',
    'Salată de vinete|salade van geroosterde aubergine|g|n|m',
    'Papanași|gefrituurde kwarkdonuts met zure room en jam|g|n|m',
    'Cozonac|zoet brood met walnoten|g|u|m',
  ],
  RU: [
    'Borsjtsj|bietensoep met kool en zure room|l|u|ma',
    'Pelmeni|deegkussentjes met gehakt|l|n',
    'Bliny|dunne pannenkoeken met zure room, zalm of jam|g|n|om',
    'Boeuf stroganoff|reepjes rundvlees in romige saus|l|n',
    'Sjtsji|koolsoep|l|u|ma',
    'Olivier-salade|aardappelsalade met erwten, ei en augurk|l|n|m',
    'Pirozjki|gevulde broodjes uit de oven of de pan|l|u|m',
    'Sjasliek|spiesen van gemarineerd vlees|l|u',
    'Haring in bontjas|gelaagde salade van haring, biet en aardappel|v|u|m',
    'Syrniki|kwarkkoekjes uit de pan|g|n|o',
  ],
  SM: [
    'Piadina|plat brood gevuld met ham, kaas en rucola|l|s|m',
    'Passatelli in brodo|deegsliertjes van broodkruim en kaas in bouillon|l|n',
    'Nidi di rondine|pastarolletjes met ham en kaas uit de oven|l|u',
    'Fagioli con le cotiche|bonen met varkenszwoerd|l|u',
    'Coniglio con finocchio|konijn met venkel uit de oven|l|u',
    'Bustrengo|taart van maismeel, appel en vijgen|g|u|m',
    'Torta Tre Monti|wafeltaart met hazelnootcrème en chocolade|g|s|m',
  ],
  RS: [
    'Ćevapi|gegrilde gehaktrolletjes in plat brood met ui|l|n',
    'Pljeskavica|grote platte hamburger van de grill|l|n',
    'Karađorđeva šnicla|opgerolde gepaneerde schnitzel met een romige vulling|l|n',
    'Sarma|koolrolletjes gevuld met gehakt en rijst|l|u',
    'Gibanica|taart van dun deeg met kaas en ei|g|u|om',
    'Prebranac|bonen uit de oven met veel ui|g|u',
    'Pasulj|bonensoep met gerookt vlees|l|u',
    'Burek|opgerold dun deeg gevuld met gehakt of kaas|l|u|o',
    'Punjene paprike|paprika gevuld met gehakt en rijst|l|u',
    'Proja|maisbrood|g|n|om',
  ],
  SK: [
    'Bryndzové halušky|aardappelgnocchi met schapenkaas en spek|l|n',
    'Kapustnica|zuurkoolsoep met worst en paddenstoelen|l|u|ma',
    'Bryndzové pirohy|deegkussentjes met schapenkaas|g|u',
    'Zemiakové placky|aardappelpannenkoekjes met knoflook|g|n',
    'Vyprážaný syr|gepaneerde gefrituurde kaas|g|n',
    'Segedínsky guláš|goulash met zuurkool en room|l|u',
    'Pečená kačica|gebraden eend met rode kool en aardappelflensjes|l|u',
    'Lokše|dunne flensjes van aardappeldeeg|g|n|m',
    'Šúľance s makom|rolletjes aardappeldeeg met maanzaad|g|n',
    'Parené buchty|gestoomde broodjes gevuld met jam|g|u',
  ],
  SI: [
    'Kranjska klobasa|gerookte worst met mosterd|l|s',
    'Štruklji|opgerold deeg met kwark, dragon of walnoten|g|u',
    'Jota|soep van zuurkool, bonen en aardappel|l|u',
    'Idrijski žlikrofi|kleine deegkussentjes met aardappelvulling|g|u',
    'Ričet|gerstsoep met bonen en gerookt vlees|l|u',
    'Žganci|pap van boekweitmeel met kaantjes|l|n',
    'Bograč|stoofpot met drie soorten vlees|l|u',
    'Potica|opgerold feestbrood met walnotenvulling|g|u|m',
    'Prekmurska gibanica|laagjestaart met maanzaad, kwark, walnoot en appel|g|u|m',
    'Blejska kremšnita|roomgebak met vanillecrème|g|u|m',
  ],
  SE: [
    'Köttbullar|gehaktballetjes met aardappelpuree, roomsaus en vossenbessen|l|n',
    'Gravad lax|gepekelde zalm met mosterd-dillesaus|v|s|m',
    'Smörgåstårta|hartige taart van brood met garnalen en ei|v|u|m',
    'Janssons frestelse|ovenschotel van aardappel, ui en ansjovis|v|u',
    'Raggmunk|aardappelpannenkoek met spek en vossenbessen|l|n',
    'Pytt i panna|blokjes aardappel, vlees en ui met een spiegelei|l|n',
    'Ärtsoppa|gele erwtensoep met spek|l|u',
    'Kroppkakor|aardappelknoedels gevuld met spek|l|u',
    'Toast Skagen|toast met garnalensalade|v|s|m',
    'Kanelbulle|kaneelbroodje|g|u|m',
  ],
  CH: [
    'Kaasfondue|gesmolten kaas met wijn, waar je brood in doopt|g|n',
    'Raclette|gesmolten kaas over aardappels met augurk|g|n',
    'Rösti|gebakken koek van geraspte aardappel|g|n',
    'Zürcher Geschnetzeltes|reepjes kalfsvlees in roomsaus met champignons|l|n',
    'Älplermagronen|macaroni met aardappel, kaas, room en appelmoes|g|n',
    'Bündner Gerstensuppe|gerstsoep met gedroogd vlees|l|u',
    'Capuns|rolletjes van snijbiet met deeg en gedroogd vlees|l|u',
    'Berner Platte|schotel met vlees, worst, zuurkool en bonen|l|u',
    'Papet vaudois|prei met aardappel en worst|l|u',
    'Birchermüesli|havermout geweekt met appel, noten en yoghurt|g|s|o',
  ],
  UA: [
    'Borsjtsj|bietensoep met kool, vlees en zure room|l|u|ma',
    'Varenyky|deegkussentjes met aardappel, kwark of kersen|g|u',
    'Holoebtsi|koolrolletjes met rijst en gehakt|l|u',
    'Kip Kiev|gepaneerde kiprol gevuld met kruidenboter|l|n',
    'Deruny|aardappelpannenkoekjes met zure room|g|n',
    'Banosj|maispap met room, schapenkaas en spek|l|n',
    'Salo|gezouten spek op roggebrood|l|s|m',
    'Pampoesjky|zachte knoflookbroodjes bij de soep|g|u',
    'Nalysnyky|dunne pannenkoekjes gevuld met kwark|g|n',
    'Syrnyky|kwarkkoekjes uit de pan|g|n|o',
  ],
  // Vaticaanstad heeft geen eigen keuken; dit zijn gerechten uit Rome, de stad eromheen.
  VA: [
    'Fettuccine alla papalina|lintpasta met ham, ei en kaas, bedacht voor een paus|l|n',
    'Cacio e pepe|pasta uit Rome met schapenkaas en zwarte peper|g|s',
    'Saltimbocca alla romana|kalfsvlees met ham en salie|l|s',
    'Carciofi alla romana|gestoofde artisjokken met munt en knoflook|g|n',
    'Supplì|gefrituurde rijstballetjes met mozzarella|g|n|m',
  ],
  XK: [
    'Flija|laagjespannenkoek, gebakken onder een hete deksel|g|u',
    'Pite|taart van dun deeg met kaas, spinazie of vlees|g|u|oma',
    'Qebapa|gegrilde gehaktrolletjes|l|n',
    'Pasul|stoofpot van bonen met gerookt vlees|l|u',
    'Sarma|koolrolletjes gevuld met gehakt en rijst|l|u',
    'Speca me mazë|paprika in roomsaus|g|n',
    'Leqenik|maisbrood met kaas|g|u|m',
    'Llokuma|gefrituurd deeg bij het ontbijt|g|n|o',
    'Bakllava|zoet gebak van dun deeg, noten en siroop|g|u|m',
  ],
});

// Azië
Object.assign(WORLD_DISHES, {
  AF: [
    'Kabuli pulao|rijst met lamsvlees, wortel en rozijnen|l|u',
    'Mantu|gestoomde deegkussentjes met gehakt en yoghurt|l|u',
    'Ashak|deegkussentjes met prei, yoghurt en gehaktsaus|l|u',
    'Bolani|plat brood gevuld met aardappel of prei, uit de pan|g|n|ma',
    'Qorma|stoofpot van vlees met ui en tomaat|l|u',
    'Kebab|spiesen van lamsvlees van de houtskool|l|n',
    'Aush|noedelsoep met bonen, yoghurt en gehaktsaus|l|u',
    'Borani banjan|gebakken aubergine in tomatensaus met yoghurt|g|n',
    'Shorwa|soep van lamsvlees en groenten|l|u',
    'Firni|melkpudding met kardemom|g|n|m',
  ],
  AM: [
    'Khorovats|gegrild vlees aan spiesen|l|u',
    'Dolma|druivenbladeren gevuld met gehakt en rijst|l|u',
    'Harissa|pap van tarwe en kip, urenlang gekookt|l|u',
    'Lavash|dun plat brood uit de kleioven|g|u|oma',
    'Khash|soep van runderpoten met knoflook|l|u|o',
    'Ghapama|pompoen gevuld met rijst, gedroogd fruit en noten|g|u',
    'Spas|yoghurtsoep met tarwe|g|n',
    'Manti|kleine deegbootjes met gehakt uit de oven|l|u',
    'Lahmajun|dun brood met gekruid gehakt|l|n|ma',
    'Gata|zoet gevuld brood|g|u|m',
  ],
  AZ: [
    'Plov|saffraanrijst met lamsvlees, gedroogd fruit en kastanjes|l|u',
    'Dolma|druivenbladeren gevuld met gehakt en rijst|l|u',
    'Qutab|dunne gevulde pannenkoek met kruiden of vlees|g|n|m',
    'Dushbara|soep met piepkleine deegkussentjes|l|u',
    'Piti|soep van lamsvlees en kikkererwten uit een aardewerken potje|l|u',
    'Lyulya kebab|spies van lamsgehakt|l|n',
    'Dovga|yoghurtsoep met kruiden|g|n',
    'Sadj|vlees en groenten op een hete ijzeren plaat|l|n',
    'Kufta bozbash|soep met grote gehaktballen en kikkererwten|l|u',
    'Pakhlava|zoet gebak met noten|g|u|m',
  ],
  BH: [
    'Machboos|gekruide rijst met kip of vis|l|u',
    'Muhammar|zoete rijst met dadelstroop, bij gebakken vis|v|n',
    'Harees|pap van tarwe en vlees|l|u',
    'Quzi|geroosterd lam op rijst|l|u',
    'Thareed|brood geweekt in stoofpot van vlees|l|u',
    'Balaleet|zoete vermicelli met omelet|g|n|o',
    'Samboosa|gefrituurde pasteitjes met vlees of groenten|l|n|m',
    'Luqaimat|deegballetjes met dadelstroop|g|n|m',
    'Halwa Bahraini|geleiachtige zoetigheid met saffraan en noten|g|u|m',
  ],
  BD: [
    'Ilish bhapa|hilsa, een vis, gestoomd in mosterdsaus|v|n',
    'Kacchi biryani|rijst met schapenvlees en aardappel, samen gegaard|l|u',
    'Bhuna khichuri|rijst met linzen, gekruid en gebakken|g|n',
    'Macher jhol|viscurry met een dunne saus|v|n',
    'Panta bhat|in water geweekte rijst met gebakken vis|v|s|o',
    'Dal|linzensoep bij de rijst|g|n',
    'Bhorta|geprakte groenten of vis met mosterdolie en chili|g|n',
    'Beef tehari|rijst met kleine stukjes rundvlees|l|u',
    'Fuchka|krokante holle balletjes gevuld met kikkererwten en tamarindewater|g|n|m',
    'Mishti doi|zoete yoghurt|g|u|m',
  ],
  BT: [
    'Ema datshi|chilipepers in kaassaus|g|n',
    'Kewa datshi|aardappel in kaassaus|g|n',
    'Shamu datshi|paddenstoelen in kaassaus|g|n',
    'Phaksha paa|varkensvlees met gedroogde chili en radijs|l|n',
    'Sikam paa|gedroogd buikspek met chili|l|n',
    'Jasha maru|pittige stoofpot van kip|l|n',
    'Momo|gestoomde deegkussentjes met vlees|l|u',
    'Hoentay|deegkussentjes van boekweit met groenten|g|u',
    'Rode rijst|nootachtige rode rijst bij elke maaltijd|g|n',
  ],
  BN: [
    'Ambuyat|kleverige sagopap die je in een zure saus doopt|g|n',
    'Nasi katok|rijst met gebakken kip en sambal|l|s|ma',
    'Nasi lemak|rijst gekookt in kokosmelk met sambal, ansjovis en ei|v|n|o',
    'Soto|kruidige soep met noedels en rundvlees|l|n',
    'Satay|vleesspiesjes met pindasaus|l|n',
    'Rendang|rundvlees in droge kokossaus|l|u',
    'Kuih|zoete hapjes van rijstmeel en kokos|g|u|m',
  ],
  KH: [
    'Amok trey|vis gestoomd in kokoscurry, in bananenblad|v|n',
    'Lok lak|blokjes rundvlees met saus van limoen en peper|l|n',
    'Kuy teav|noedelsoep met varkensvlees bij het ontbijt|l|n|o',
    'Bai sach chrouk|rijst met gegrild varkensvlees|l|n|o',
    'Nom banh chok|rijstnoedels met groene viscurry|v|n|om',
    'Samlor korko|soep met veel groenten en vis|v|u',
    'Kdam chaa|gebakken krab met groene peper|v|n',
    'Prahok ktis|dip van gefermenteerde vis, varkensgehakt en kokos|l|n',
    'Lap Khmer|salade van gemarineerd rundvlees met limoen|l|s',
    'Num pang|stokbroodje met vlees en zuur|l|s|m',
  ],
  GE: [
    'Khachapuri|brood gevuld met gesmolten kaas, soms met een ei|g|u|oma',
    'Khinkali|grote deegbuideltjes met gehakt en bouillon|l|u',
    'Mtsvadi|spiesen van gegrild vlees|l|n',
    'Lobio|stoofpot van kidneybonen met kruiden|g|u',
    'Pkhali|balletjes van groenten en walnoot|g|n|m',
    'Badrijani nigvzit|rolletjes aubergine met walnotenpasta|g|n|m',
    'Chakhokhbili|kip gestoofd met tomaat en kruiden|l|u',
    'Kharcho|soep van rundvlees, rijst en walnoot|l|u',
    'Shkmeruli|kip in een saus van knoflook en melk|l|n',
    'Churchkhela|snoer van noten in ingedikt druivensap|g|u|m',
  ],
  IR: [
    'Chelo kabab|rijst met spiesen van lams- of rundvlees|l|n',
    'Ghormeh sabzi|stoofpot van kruiden, bonen en lamsvlees|l|u',
    'Fesenjan|kip in saus van walnoot en granaatappel|l|u',
    'Tahdig|rijst met een krokante korst van de bodem van de pan|g|n',
    'Zereshk polo|rijst met zure besjes en kip|l|u',
    'Ash reshteh|dikke soep met noedels, bonen en kruiden|g|u',
    'Gheimeh|stoofpot van spliterwten en vlees met frietjes|l|u',
    'Kuku sabzi|kruidenomelet|g|n|ma',
    'Dizi|stoofpot van lamsvlees en kikkererwten, fijngestampt|l|u',
    'Mirza ghasemi|gerookte aubergine met tomaat, knoflook en ei|g|n',
  ],
  IQ: [
    'Masgouf|karper, opengeklapt en gegrild bij open vuur|v|u',
    'Dolma|gevulde groenten en druivenbladeren|l|u',
    'Quzi|langzaam gegaard lam op rijst met noten|l|u',
    'Tashreeb|brood geweekt in bouillon met vlees|l|u',
    'Kubba|ballen van bulgur of rijst gevuld met gehakt|l|u',
    'Tepsi baytinijan|ovenschotel van aubergine en gehaktballetjes|l|u',
    'Bamia|okra gestoofd met lamsvlees en tomaat|l|u',
    'Biryani|rijst met kip, erwten, vermicelli en noten|l|u',
    'Kahi met geymar|deeg in laagjes met dikke room en siroop|g|n|o',
    'Kleicha|koekjes met dadels|g|u|m',
  ],
  IL: [
    'Falafel|gefrituurde balletjes van kikkererwten in pitabrood|g|n|ma',
    'Shakshuka|eieren gepocheerd in pittige tomatensaus|g|n|om',
    'Hummus|puree van kikkererwten met sesampasta|g|n|ma',
    'Sabich|pita met gebakken aubergine en ei|g|s|om',
    'Shoarma|gegrild vlees van het spit in pita|l|n',
    'Schnitzel|gepaneerde kipschnitzel|l|n',
    'Cholent|stoofpot voor de sjabbat met bonen en vlees|l|u',
    'Jachnun|opgerold deeg, een nacht lang gegaard|g|u|o',
    'Bourekas|deeghapjes met kaas of aardappel|g|u|om',
    'Malabi|melkpudding met rozenwater|g|n|m',
  ],
  JO: [
    'Mansaf|lamsvlees in saus van gedroogde yoghurt op rijst|l|u',
    'Maqluba|omgekeerde pan rijst met vlees en aubergine|l|u',
    'Zarb|vlees en groenten gegaard in een oven onder het zand|l|u',
    'Musakhan|kip met sumak en ui op plat brood|l|u',
    'Falafel|gefrituurde balletjes van kikkererwten|g|n|oma',
    'Hummus|puree van kikkererwten met sesampasta|g|n|oma',
    'Fattet hummus|brood met kikkererwten en yoghurt|g|n|o',
    'Galayet bandora|tomaten gebakken met ui en olijfolie|g|s',
    'Mujaddara|linzen met rijst en gebakken ui|g|n',
    'Kunafa|warm gebak van kaas en dun deeg met siroop|g|u|m',
  ],
  KZ: [
    'Beshbarmak|gekookt vlees op brede noedels met uienbouillon|l|u',
    'Kazy|worst van paardenvlees|l|u',
    'Plov|rijst met vlees en wortel|l|u',
    'Manty|gestoomde deegkussentjes met vlees|l|u',
    'Kuurdak|gebakken vlees met ui en aardappel|l|n',
    'Lagman|getrokken noedels met vlees en groenten|l|u',
    'Shashlik|spiesen van de houtskool|l|n',
    'Sorpa|bouillon van lamsvlees|l|u',
    'Baursak|gefrituurde deegbolletjes|g|n|om',
    'Kurt|gedroogde zoute kaasballetjes|g|u|m',
  ],
  KW: [
    'Machboos|gekruide rijst met kip, lam of vis|l|u',
    'Murabyan|rijst met garnalen|v|n',
    'Mutabbaq samak|gebakken vis op gekruide rijst|v|n',
    'Harees|pap van tarwe en vlees|l|u',
    'Jireesh|gebroken tarwe gekookt met kip en tomaat|l|u',
    'Margoog|stoofpot van vlees en groenten met dunne lapjes deeg|l|u',
    'Balaleet|zoete vermicelli met omelet|g|n|o',
    'Luqaimat|deegballetjes met siroop|g|n|m',
    'Gers ogaily|cake met saffraan, kardemom en sesam|g|u|m',
  ],
  KG: [
    'Beshbarmak|gekookt vlees op noedels met bouillon|l|u',
    'Plov|rijst met lamsvlees en wortel|l|u',
    'Lagman|getrokken noedels met vlees en groenten|l|u',
    'Manty|gestoomde deegkussentjes met vlees|l|u',
    'Samsa|pasteitjes met vlees uit de kleioven|l|u|m',
    'Kuurdak|gebakken vlees met ui en aardappel|l|n',
    'Shorpo|soep van lamsvlees en groenten|l|u',
    'Oromo|gestoomde deegrol met vulling|l|u',
    'Ashlyam-fu|koude pittige noedelsoep|g|n|m',
    'Boorsok|gefrituurde deegblokjes|g|n|om',
  ],
  LA: [
    'Larb|salade van gehakt vlees met limoen, munt en geroosterde rijst|l|n',
    'Tam mak hoong|pittige salade van groene papaja met vissaus|v|s',
    'Khao niao|kleefrijst, met de hand gegeten|g|n',
    'Khao piak sen|soep met dikke rijstnoedels en kip|l|n|o',
    'Or lam|stoofpot met vlees, aubergine en kruiden|l|u',
    'Mok pa|vis gestoomd in bananenblad|v|n',
    'Ping kai|gegrilde kip|l|n',
    'Khao soi|noedelsoep met tomaat en gehakt|l|n',
    'Sai oua|kruidige worst|l|n',
    'Nam khao|krokante rijstsalade met zure worst|l|n',
  ],
  MY: [
    'Nasi lemak|rijst in kokosmelk met sambal, ansjovis, pinda en ei|v|n|o',
    'Satay|vleesspiesjes met pindasaus|l|n',
    'Laksa|pittige noedelsoep met kokos of tamarinde|v|n',
    'Char kway teow|gebakken platte rijstnoedels met garnalen|v|s',
    'Roti canai|bladerig plat brood met currysaus|g|n|o',
    'Rendang|rundvlees in droge kokossaus|l|u',
    'Mee goreng mamak|gebakken noedels met ei en groenten|l|s',
    'Bak kut teh|kruidensoep met varkensribben|l|u',
    'Ikan bakar|gegrilde vis met sambal|v|n',
    'Cendol|geschaafd ijs met kokosmelk en groene sliertjes|g|s|m',
  ],
  MV: [
    'Mas huni|tonijn met kokos, ui en chili bij het ontbijt|v|s|o',
    'Garudhiya|heldere tonijnbouillon met rijst|v|n',
    'Mas riha|tonijncurry met kokosmelk|v|n',
    'Fihunu mas|gegrilde vis met chilipasta|v|n',
    'Rihaakuru|dikke pasta van ingekookte tonijn|v|u',
    'Roshi|dun plat brood|g|n|o',
    'Bis keemiya|pasteitje met ei, tonijn en kool|v|n|m',
    'Gulha|gefrituurde balletjes gevuld met tonijn|v|n|m',
    'Kulhi boakibaa|pittige viskoek|v|u|m',
    'Saagu bondibai|sagopudding met kokosmelk|g|n|m',
  ],
  MN: [
    'Buuz|gestoomde deegkussentjes met schapenvlees|l|u',
    'Khuushuur|gefrituurde pasteitjes met vlees|l|n',
    'Tsuivan|gebakken noedels met vlees en groenten|l|n',
    'Khorkhog|schapenvlees gegaard met hete stenen|l|u',
    'Boodog|geit, van binnenuit gegaard met hete stenen|l|u',
    'Bansh|kleine gekookte deegkussentjes|l|n',
    'Guriltai shul|noedelsoep met schapenvlees|l|n',
    'Budaatai khuurga|gebakken rijst met vlees|l|n',
    'Boortsog|gefrituurde deegkoekjes|g|n|om',
    'Aaruul|gedroogde wrongel|g|u|m',
  ],
  MM: [
    'Mohinga|vissoep met rijstnoedels bij het ontbijt|v|n|o',
    'Lahpet thoke|salade van gefermenteerde theebladeren|g|s|m',
    'Shan-noedels|rijstnoedels met kip of varkensvlees in tomatensaus|l|n',
    'Ohn no khao swe|noedels in soep van kokos en kip|l|n',
    'Nan gyi thoke|salade van dikke noedels met kipcurry|l|n',
    'Kyet thar hin|kipcurry met veel ui|l|u',
    'Htamin jin|gefermenteerde rijst met tomaat en vis|v|n',
    'Tofu nway|warme tofu van kikkererwten over noedels|g|n',
    'Samosa thoke|salade van samosa en kikkererwten|g|s|m',
    'Mont lin ma yar|kleine pannenkoekjes met kwartelei|g|n|m',
  ],
  NP: [
    'Dal bhat|rijst met linzensoep en groenten|g|n',
    'Momo|gestoomde deegkussentjes met vlees of groenten|l|u',
    'Thukpa|noedelsoep met vlees|l|n',
    'Chatamari|rijstpannenkoek met gehakt en ei|l|n',
    'Choila|pittig gegrild buffelvlees|l|n',
    'Gundruk|gefermenteerde bladgroente, vaak als soep|g|n',
    'Dhido|stevige pap van boekweit of gierst|g|n',
    'Aloo tama|curry van aardappel en bamboescheuten|g|n',
    'Sel roti|ring van rijstdeeg, gefrituurd|g|n|om',
    'Yomari|gestoomd rijstdeeg gevuld met stroop en sesam|g|u|m',
  ],
  KP: [
    'Pyongyang naengmyeon|koude noedels van boekweit in bouillon|l|n',
    'Onban|warme rijst met kip en paddenstoelen in bouillon|l|n',
    'Kimchi|gefermenteerde kool|g|u',
    'Injo gogi bap|rijst in een vel van soja|g|n|m',
    'Dubu bap|rijst in gebakken tofu met chilisaus|g|n|m',
    'Nokdu jijim|pannenkoek van mungbonen|g|n',
    'Mandu|deegkussentjes met vlees|l|u',
    'Sundae|bloedworst met noedels|l|u',
  ],
  OM: [
    'Shuwa|lamsvlees, lang gegaard in een kuil met houtskool|l|u',
    'Majboos|gekruide rijst met kip of vlees|l|u',
    'Harees|pap van tarwe en vlees|l|u',
    'Mashuai|gegrilde vis met citroenrijst|v|n',
    'Mishkak|spiesjes gemarineerd vlees van de grill|l|n',
    'Madrouba|rijst tot pap gekookt met kip|l|u',
    'Thareed|brood geweekt in stoofpot van vlees|l|u',
    'Khubz rakhal|flinterdun brood, vaak met ei en kaas|g|s|o',
    'Luqaimat|deegballetjes met dadelstroop|g|n|m',
    'Omaanse halwa|geleiachtige zoetigheid met rozenwater en noten|g|u|m',
  ],
  PK: [
    'Biryani|gekruide rijst met vlees|l|u',
    'Nihari|rundvlees, een nacht gestoofd en gegeten bij het ontbijt|l|u|o',
    'Karahi|kip of schapenvlees met tomaat en gember uit de wok|l|n',
    'Haleem|dikke pap van tarwe, linzen en vlees|l|u',
    'Seekh kebab|spies van gekruid gehakt|l|n',
    'Chapli kebab|platte kruidige schijf gehakt|l|n',
    'Sajji|hele kip of lam aan het spit|l|u',
    'Daal chawal|linzen met rijst|g|n',
    'Saag met maisbrood|gestoofde mosterdbladeren met plat brood van mais|g|u',
    'Halwa puri|gefrituurd brood met zoete griesmeel en kikkererwten|g|n|o',
  ],
  PS: [
    'Musakhan|kip met sumak en ui op plat brood|l|u',
    'Maqluba|omgekeerde pan rijst met vlees en groenten|l|u',
    'Qidreh|rijst met lamsvlees en kikkererwten uit een koperen pot|l|u',
    'Sumaghiyyeh|stoofpot van vlees, snijbiet en sumak|l|u',
    'Warak enab|druivenbladeren gevuld met rijst en vlees|l|u',
    'Falafel|gefrituurde balletjes van kikkererwten|g|n|oma',
    'Hummus|puree van kikkererwten met sesampasta|g|n|oma',
    'Mujaddara|linzen met rijst en gebakken ui|g|n',
    'Manakish|plat brood met tijm en olijfolie|g|n|o',
    'Knafeh|warm gebak van kaas en dun deeg met siroop|g|u|m',
  ],
  PH: [
    'Adobo|kip of varkensvlees gestoofd in azijn, sojasaus en knoflook|l|u',
    'Sinigang|zure soep met tamarinde en varkensvlees of garnalen|l|u',
    'Lechon|heel geroosterd speenvarken|l|u',
    'Pancit|gebakken noedels met groenten en vlees|l|n',
    'Lumpia|loempia met vlees en groenten|l|n|m',
    'Kare-kare|stoofpot van ossenstaart in pindasaus|l|u',
    'Sisig|fijngehakt varkensvlees op een hete plaat|l|n',
    'Tinola|kippensoep met gember en papaja|l|n',
    'Tapsilog|gedroogd rundvlees met knoflookrijst en ei|l|n|o',
    'Halo-halo|geschaafd ijs met fruit, bonen en melk|g|s|m',
  ],
  QA: [
    'Machboos|gekruide rijst met kip of lam|l|u',
    'Harees|pap van tarwe en vlees|l|u',
    'Thareed|brood geweekt in stoofpot van vlees en groenten|l|u',
    'Madrouba|rijstpap met kip en kardemom|l|u',
    'Saloona|pittige stoofpot van vlees en groenten|l|u',
    'Balaleet|zoete vermicelli met omelet|g|n|o',
    'Luqaimat|deegballetjes met siroop|g|n|m',
    'Khanfaroosh|gefrituurde koekjes met saffraan en kardemom|g|n|m',
  ],
  SA: [
    'Kabsa|gekruide rijst met kip of lam|l|u',
    'Mandi|vlees en rijst uit een kuiloven|l|u',
    'Jareesh|gebroken tarwe gekookt met yoghurt en vlees|l|u',
    'Saleeg|romige rijst gekookt in melk, met kip|l|u',
    'Harees|pap van tarwe en vlees|l|u',
    'Matazeez|lapjes deeg in een stoofpot van vlees en groenten|l|u',
    'Mutabbaq|gevouwen gevulde pannenkoek|l|n|m',
    'Foul met tamees|tuinbonen met een groot plat brood|g|n|o',
    'Masoub|pap van banaan en brood met room en honing|g|s|o',
    'Maamoul|koekjes gevuld met dadels|g|u|m',
  ],
  SG: [
    'Hainanese kiprijst|gepocheerde kip op rijst gekookt in bouillon|l|n',
    'Chili crab|krab in zoetpittige tomatensaus|v|n',
    'Laksa|pittige kokossoep met noedels en garnalen|v|n',
    'Char kway teow|gebakken platte rijstnoedels met garnalen|v|s',
    'Hokkien mee|gebakken noedels met garnalen en inktvis|v|n',
    'Bak kut teh|pepersoep met varkensribben|l|u',
    'Satay|vleesspiesjes met pindasaus|l|n',
    'Roti prata|bladerig plat brood met curry|g|n|o',
    'Chai tow kway|gebakken koek van radijs met ei|g|n',
    'Kaya toast|toast met kokosjam en zachtgekookte eieren|g|s|o',
  ],
  LK: [
    'Rijst en curry|rijst met een reeks kleine curry\'s van groenten, linzen en vis|v|u',
    'Hoppers|komvormige pannenkoek van rijstmeel, vaak met een ei|g|n|oa',
    'String hoppers|nestjes gestoomde rijstnoedels met curry|g|n|o',
    'Kottu roti|fijngehakt plat brood gebakken met groenten, ei en vlees|l|n',
    'Parippu|linzencurry met kokosmelk|g|n',
    'Pol sambol|geraspte kokos met chili en limoen|g|s',
    'Lamprais|rijst met curry, gebakken in bananenblad|l|u',
    'Ambul thiyal|zure droge viscurry|v|n',
    'Kiribath|rijst gekookt in kokosmelk|g|n|o',
    'Watalappam|pudding van kokosmelk en palmsuiker|g|u|m',
  ],
  SY: [
    'Kibbeh|balletjes van bulgur en gehakt|l|u',
    'Fattoush|salade met geroosterd brood en sumak|g|s',
    'Shoarma|gegrild vlees van het spit in plat brood|l|n',
    'Yabraq|druivenbladeren gevuld met rijst en vlees|l|u',
    'Mahshi|courgette en aubergine gevuld met rijst en gehakt|l|u',
    'Kebab karaz|gehaktballetjes in kersensaus|l|n',
    'Shish barak|deegkussentjes met vlees in yoghurtsaus|l|u',
    'Muhammara|dip van rode paprika en walnoten|g|n|m',
    'Fatteh|brood met kikkererwten, yoghurt en pijnboompitten|g|n|o',
    'Halawet el jibn|zoete rolletjes van kaas met room|g|u|m',
  ],
  TW: [
    'Rundvleesnoedelsoep|noedels in bouillon met gestoofd rundvlees|l|u',
    'Lu rou fan|rijst met gestoofd varkensgehakt in sojasaus|l|u',
    'Xiao long bao|gestoomde deegbuideltjes met soep erin|l|u',
    'Gua bao|gestoomd broodje met buikspek en pinda|l|n|m',
    'Oesteromelet|omelet met oesters en zoete saus|v|n',
    'San bei ji|kip met sesamolie, sojasaus en basilicum|l|n',
    'Ji pai|grote gepaneerde kipfilet van de nachtmarkt|l|n|m',
    'Stinkende tofu|gefermenteerde tofu, gefrituurd|g|n|m',
    'Cong you bing|bladerige pannenkoek met lente-ui|g|n|om',
    'Ananascake|koekje gevuld met ananasjam|g|u|m',
  ],
  TJ: [
    'Qurutob|brood in saus van gedroogde yoghurt met ui en groenten|g|n',
    'Osh|rijst met lamsvlees, wortel en kikkererwten|l|u',
    'Laghman|getrokken noedels met vlees en groenten|l|u',
    'Sambusa|pasteitjes met vlees uit de kleioven|l|u|m',
    'Shurbo|soep van lamsvlees en groenten|l|u',
    'Mantu|gestoomde deegkussentjes met vlees|l|u',
    'Mastoba|rijstsoep met vlees en yoghurt|l|u',
    'Non|rond brood uit de kleioven|g|u|oma',
  ],
  TL: [
    'Ikan sabuko|gegrilde makreel met tamarinde, basilicum en chili|v|n',
    'Batar daan|stoofpot van mais, mungbonen en pompoen|g|u',
    'Caril|milde kipcurry met kokos|l|u',
    'Feijoada|bonenstoofpot met varkensvlees|l|u',
    'Tukir|geitenvlees gegaard in bamboe|l|u',
    'Katupa|rijst gekookt in kokosmelk in een palmblad|g|n',
    'Bibinka|gegrilde kokoscake|g|u|m',
  ],
  TM: [
    'Palaw|rijst met lamsvlees en wortel|l|u',
    'Dograma|soep met verkruimeld brood, vlees en ui|l|u',
    'Ichlekli|platte pastei met vlees|l|u',
    'Fitchi|ronde vleespastei|l|u',
    'Manty|gestoomde deegkussentjes met vlees|l|u',
    'Shurpa|soep van lamsvlees en groenten|l|u',
    'Gutap|halvemaanvormige gevulde pannenkoek|g|n|m',
    'Çörek|rond brood uit de kleioven|g|u|oma',
  ],
  AE: [
    'Machboos|gekruide rijst met kip, lam of vis|l|u',
    'Harees|pap van tarwe en vlees|l|u',
    'Thareed|brood geweekt in stoofpot van vlees en groenten|l|u',
    'Khuzi|geroosterd lam op rijst met noten|l|u',
    'Madrooba|gezouten vis, tot saus gekookt met kruiden|v|u',
    'Samak mashwi|gegrilde vis|v|n',
    'Balaleet|zoete vermicelli met omelet|g|n|o',
    'Chebab|pannenkoekjes met saffraan en dadelstroop|g|n|o',
    'Regag|flinterdun krokant brood met ei of kaas|g|s|o',
    'Luqaimat|deegballetjes met dadelstroop|g|n|m',
  ],
  UZ: [
    'Plov|rijst met lamsvlees, wortel en kikkererwten uit een grote ketel|l|u',
    'Samsa|pasteitjes met vlees uit de kleioven|l|u|m',
    'Lagman|getrokken noedels met vlees en groenten|l|u',
    'Manti|gestoomde deegkussentjes met lamsvlees|l|u',
    'Shashlik|spiesen van de houtskool|l|n',
    'Shurpa|soep van lamsvlees en groenten|l|u',
    'Dimlama|stoofpot van vlees en groenten in lagen|l|u',
    'Chuchvara|kleine deegkussentjes in bouillon|l|n',
    'Norin|koude fijngesneden noedels met paardenvlees|l|u',
    'Non|rond brood met een stempel uit de kleioven|g|u|oma',
  ],
  YE: [
    'Saltah|borrelende stoofpot met vlees en schuim van fenegriek|l|u',
    'Mandi|vlees en rijst uit een kuiloven|l|u',
    'Fahsa|stoofpot van draadjesvlees in een stenen pot|l|u',
    'Haneeth|langzaam geroosterd lam op rijst|l|u',
    'Zurbian|rijst met lamsvlees en aardappel|l|u',
    'Shafoot|brood in yoghurt met kruiden|g|s|m',
    'Aseed|bal van deeg met bouillon|g|n',
    'Fasolia|bonen met ei bij het ontbijt|g|n|o',
    'Malawach|bladerig plat brood uit de pan|g|n|o',
    'Bint al-sahn|brood in laagjes met honing|g|u|m',
  ],
});

