'use strict';

// Gegevens voor de wereldkeuken: een eenvoudige wereldkaart en per land tien bekende gerechten.

// De omtrek van het land per werelddeel, als punten [lengtegraad, breedtegraad]. Het is een grove,
// hoekige tekening: genoeg om de werelddelen te herkennen en aan te tikken, niet om op te navigeren.
const LAND = {
  'noord-amerika': [
    [[-168, 66], [-158, 71], [-141, 70], [-128, 70], [-115, 68], [-95, 69], [-85, 66], [-94, 59], [-92, 56], [-82, 52], [-79, 56], [-77, 62], [-73, 62], [-64, 60], [-56, 52], [-66, 45], [-70, 42], [-75, 36], [-81, 31], [-80, 25], [-82, 29], [-90, 30], [-97, 26], [-97, 20], [-94, 18], [-88, 21], [-87, 16], [-83, 10], [-78, 8], [-85, 11], [-92, 15], [-105, 20], [-106, 23], [-112, 29], [-117, 33], [-122, 37], [-124, 43], [-124, 48], [-130, 54], [-140, 60], [-152, 58], [-160, 58], [-166, 62]],
    [[-73, 78], [-60, 82], [-30, 83], [-18, 80], [-20, 70], [-40, 65], [-44, 60], [-52, 65], [-55, 70], [-68, 76]],
  ],
  'zuid-amerika': [
    [[-78, 8], [-72, 12], [-62, 10], [-52, 5], [-50, 0], [-35, -6], [-39, -15], [-41, -22], [-48, -28], [-53, -34], [-58, -38], [-65, -42], [-66, -48], [-69, -52], [-72, -54], [-75, -50], [-73, -40], [-71, -30], [-70, -18], [-76, -13], [-81, -5], [-80, 0], [-77, 4]],
  ],
  europa: [
    // Het vasteland, met de Oostzee als inham tussen Scandinavië en de rest
    [[-9, 37], [-9, 43], [-1, 43.5], [-1, 46], [-4.5, 48.5], [-1.5, 49.5], [2, 51], [4, 52.5], [7, 53.5], [8.5, 55], [8.2, 57], [10.5, 57.5], [10, 55], [11, 54], [14, 54], [18.5, 54.5], [21, 55], [21, 57], [24, 58], [23.5, 59.5], [30, 60], [25, 60.3], [22, 60], [21, 61.5], [21.5, 63], [25, 65.5], [22, 65.8], [18, 62.5], [17, 61], [18.5, 60], [18, 59], [16.5, 57.5], [16, 56.2], [13, 55.4], [12.5, 56.5], [11.5, 58], [11, 59], [8, 58], [5, 59], [5, 62], [8, 63.5], [12, 66], [15, 68.5], [20, 70], [25, 71], [31, 70.5], [41, 67.5], [44, 68], [60, 69], [60, 52], [48, 46], [47, 42], [40, 43.5], [33, 45], [30, 46], [28, 43.5], [28, 41], [26, 40.5], [24, 40], [23, 38], [22, 36.5], [20, 39], [19.5, 42], [14, 45], [13.5, 45.5], [12.5, 44], [16, 41], [18, 40], [16, 38], [15.5, 40], [12, 42], [9, 44], [3, 43], [3, 41.5], [0, 39], [-2, 36.7], [-5.5, 36]],
    [[-5.5, 50], [1.5, 51.2], [0, 53.5], [-2, 56], [-3, 58.5], [-6, 57.5], [-5, 54.5], [-3, 53.5], [-5, 52]],
    [[-10, 52], [-6, 52], [-6, 55], [-8.5, 55], [-10, 54]],
    [[-24, 65.5], [-14, 65], [-15, 64], [-22, 63.5]],
  ],
  afrika: [
    [[-6, 35], [10, 37], [20, 32], [32, 31], [35, 24], [37, 20], [43, 12], [51, 12], [48, 5], [41, -2], [40, -10], [40, -15], [35, -24], [33, -27], [28, -33], [20, -35], [17, -30], [12, -18], [13, -8], [9, -1], [9, 4], [3, 6], [-4, 5], [-8, 4], [-13, 8], [-17, 14], [-17, 21], [-13, 27], [-10, 30]],
    [[49, -12], [50, -16], [47, -25], [44, -23], [44, -17]],
  ],
  azie: [
    [[60, 69], [70, 73], [90, 76], [105, 78], [115, 74], [140, 73], [160, 70], [180, 69], [179, 65], [170, 60], [163, 58], [157, 51], [156, 57], [143, 59], [135, 54], [141, 48], [130, 43], [129, 36], [126, 34.5], [126, 38], [121, 39], [118, 38], [122, 37], [121, 31], [119, 25], [114, 22.5], [108, 21.5], [106, 19], [109, 12], [105, 9], [103, 11], [100, 13.5], [99.5, 9], [100, 6.5], [103.5, 1.5], [101, 3], [98.5, 8], [98, 16], [94, 16], [92, 22], [87, 21], [80.5, 15.5], [80, 10], [77.5, 8], [73, 16], [72.5, 21], [67, 24], [61, 25], [57, 27], [50, 30], [48, 30], [50, 26.5], [54, 24], [56.3, 26], [59.5, 22.5], [52, 17], [45, 13], [43, 13], [39, 21], [35, 28], [34.5, 31], [36, 36], [30, 36.5], [27, 37], [26, 40.5], [29, 41], [36, 41.5], [41, 41.5], [40, 43.5], [47, 42], [48, 46], [60, 52]],
    [[130, 31.5], [131, 34], [136, 36], [140, 41], [142, 45.5], [145, 43.5], [141, 38], [140, 35.5], [135, 34], [131.5, 31.5]],
    [[80, 9.5], [82, 7.5], [80.5, 6]],
    [[121, 18.5], [122, 14], [126, 7], [122, 7], [120, 14]],
    [[95, 5.5], [104, -2], [106, -6], [102, -4], [97, 2]],
    [[105.5, -6.5], [114.5, -7.5], [114.5, -8.5], [106, -7.5]],
    [[109, 1.5], [117, 7], [119, 1], [116, -4], [110, -3]],
    [[120, 1], [125, 1.5], [121.5, -3], [123, -5], [120, -5.5], [119.5, -1]],
  ],
  oceanie: [
    [[114, -22], [122, -17], [129, -15], [131, -12], [136.5, -12], [136, -15], [141, -17], [142.5, -11], [146, -19], [153, -25], [153.5, -29], [150, -37], [146, -39], [140, -38], [135.5, -35], [131, -31.5], [124, -33], [118, -35], [115, -34], [113.5, -26]],
    [[145, -41], [148, -41], [147, -43.5], [146, -43.5]],
    [[173, -35], [178, -38], [175, -41.5], [173.5, -39.5]],
    [[173, -41], [174, -42], [170.5, -46], [166.5, -46], [168.5, -44]],
    [[131, -1], [141, -2.5], [150.5, -6], [147, -10], [141, -9], [138, -7], [133, -4]],
  ],
};

// Per werelddeel: de naam, het stuk kaart dat je ziet na het aantikken ([west, oost, zuid, noord]) en de
// landen. Een land is [landcode, naam, lengtegraad, breedtegraad, gerechten]; de plek is waar het vlaggetje
// staat, soms een stukje opgeschoven zodat vlaggetjes elkaar niet overlappen.
// Een gerecht is 'naam|omschrijving|soort|tijd|maaltijden', met soort l (vlees), v (vis) of g (vegetarisch),
// tijd s (snel), n (gemiddeld) of u (uitgebreid) en maaltijden o, m en a (weggelaten betekent avondeten).
// De tien gerechten per land zijn een eigen keuze van bekende gerechten, geen officiële ranglijst.
const WORLD = {
  europa: { name: 'Europa', box: [-16, 42, 34, 61], countries: [
    ['NL', 'Nederland', 5.5, 53.3, [
      'Stamppot boerenkool|aardappelpuree met boerenkool en rookworst|l|n',
      'Erwtensoep|dikke soep van spliterwten met rookworst|l|u|ma',
      'Hutspot|stamppot van aardappel, wortel en ui|l|n',
      'Pannenkoeken|grote dunne pannenkoeken, zoet of hartig|g|n|ma',
      'Kibbeling|gefrituurde stukjes witvis met saus|v|s|ma',
      'Hollandse nieuwe|rauwe haring met uitjes|v|s|m',
      'Bitterballen|krokante ragoutballetjes met mosterd|l|s|m',
      'Poffertjes|kleine luchtige pannenkoekjes met poedersuiker|g|n|m',
      'Hachee|stoofvlees met veel ui en laurier|l|u',
      'Broodje kroket|zacht broodje met een rundvleeskroket|l|s|m',
    ]],
    ['BE', 'België', 1.8, 49.6, [
      'Stoofvlees met friet|rundvlees gestoofd in bier, met frieten|l|u',
      'Mosselen met friet|gekookte mosselen met frieten|v|n',
      'Waterzooi|romige stoofpot met kip en groenten|l|u',
      'Witlof met ham en kaas|witlof in ham gerold, met kaassaus uit de oven|l|u',
      'Vol-au-vent|bladerdeegbakje met kipragout|l|u',
      'Konijn met pruimen|konijn gestoofd met pruimen|l|u',
      'Tomaat-garnaal|tomaat gevuld met grijze garnalen|v|s|m',
      'Balletjes in tomatensaus|gehaktballetjes in tomatensaus|l|n',
      'Stoemp met worst|aardappelpuree met groenten en braadworst|l|n',
      'Luikse wafels|zoete wafels met parelsuiker|g|n|om',
    ]],
    ['FR', 'Frankrijk', 2, 45.2, [
      'Coq au vin|kip gestoofd in rode wijn|l|u',
      'Boeuf bourguignon|rundvlees gestoofd in rode wijn|l|u',
      'Ratatouille|gestoofde groenten uit de Provence|g|n',
      'Quiche lorraine|hartige taart met spek en ei|l|u|ma',
      'Croque-monsieur|tosti met ham, kaas en bechamelsaus|l|s|m',
      'Bouillabaisse|vissoep uit Marseille|v|u',
      'Cassoulet|stoofpot van witte bonen, worst en eend|l|u',
      'Crêpes|dunne pannenkoeken, zoet of hartig|g|n|om',
      'Franse uiensoep|soep van gekarameliseerde ui met kaasbroodje|l|u|ma',
      'Tartiflette|aardappelgratin met spek en kaas|l|u',
    ]],
    ['IT', 'Italië', 12.5, 42.6, [
      'Pizza margherita|pizza met tomaat, mozzarella en basilicum|g|n',
      'Spaghetti carbonara|pasta met ei, spek en pecorino|l|s',
      'Lasagne|laagjes pasta met gehaktsaus en bechamel|l|u',
      'Risotto met paddenstoelen|romige rijst met paddenstoelen|g|n',
      'Spaghetti bolognese|pasta met saus van gehakt en tomaat|l|n',
      'Gnocchi|aardappelknoedels met saus|g|n',
      'Ossobuco|kalfsschenkel gestoofd met groenten|l|u',
      'Minestrone|stevige groentesoep met pasta|g|n|ma',
      'Parmigiana di melanzane|ovenschotel van aubergine, tomaat en kaas|g|u',
      'Saltimbocca|kalfsvlees met ham en salie|l|s',
    ]],
    ['ES', 'Spanje', -3.5, 40, [
      'Paella|rijst met saffraan, kip en zeevruchten|v|u',
      'Tortilla española|dikke omelet met aardappel en ui|g|n|ma',
      'Gazpacho|koude soep van tomaat en groenten|g|s|m',
      'Patatas bravas|gebakken aardappels met pittige saus|g|n|m',
      'Gambas al ajillo|garnalen in knoflookolie|v|s',
      'Pulpo a la gallega|octopus met paprikapoeder en aardappel|v|u',
      'Albondigas|gehaktballetjes in tomatensaus|l|n',
      'Fabada asturiana|stoofpot van witte bonen en worst|l|u',
      'Croquetas|kroketjes met ham|l|n|m',
      'Pisto|gestoofde groenten met een ei|g|n',
    ]],
    ['PT', 'Portugal', -10.5, 39.3, [
      'Bacalhau à brás|kabeljauw met aardappel en ei|v|n',
      'Caldo verde|soep van aardappel, kool en chorizo|l|n|ma',
      'Francesinha|sandwich met vlees, kaas en biersaus|l|n',
      'Sardinhas assadas|gegrilde sardines|v|s',
      'Arroz de marisco|rijst met zeevruchten|v|u',
      'Cozido à portuguesa|stoofpot van vlees, worst en groenten|l|u',
      'Frango piri-piri|gegrilde kip met pittige saus|l|u',
      'Bifana|broodje met gemarineerd varkensvlees|l|s|m',
      'Polvo à lagareiro|octopus uit de oven met aardappel|v|u',
      'Pastel de nata|bladerdeegtaartje met custard|g|u|om',
    ]],
    ['DE', 'Duitsland', 12.5, 51.3, [
      'Schnitzel|gepaneerde lap kalfs- of varkensvlees|l|n',
      'Bratwurst met zuurkool|braadworst met zuurkool en mosterd|l|n',
      'Sauerbraten|gemarineerd rundvlees, lang gestoofd|l|u',
      'Käsespätzle|eiernoedels met kaas en gebakken ui|g|n',
      'Currywurst|worst met curryketchup en friet|l|s|ma',
      'Kartoffelsalat|aardappelsalade met spek|l|n|ma',
      'Rouladen|rundvleesrolletjes met spek en augurk|l|u',
      'Maultaschen|gevulde deegkussentjes|l|n',
      'Eisbein|gekookte varkensschenkel met zuurkool|l|u',
      'Flammkuchen|dunne bodem met zure room, ui en spek|l|n',
    ]],
    ['GB', 'Verenigd Koninkrijk', -3, 54.5, [
      'Fish and chips|gefrituurde vis met dikke frieten|v|n',
      'Full English breakfast|eieren, spek, worst, bonen en toast|l|n|o',
      'Shepherd\'s pie|lamsgehakt met een laag aardappelpuree|l|u',
      'Sunday roast|gebraden vlees met groenten en jus|l|u',
      'Chicken tikka masala|kip in romige tomaten-kerriesaus|l|n',
      'Bangers and mash|worstjes met aardappelpuree en uienjus|l|n',
      'Beef Wellington|ossenhaas in bladerdeeg|l|u',
      'Cornish pasty|deegflap gevuld met vlees en groenten|l|u|ma',
      'Toad in the hole|worstjes in gebakken beslag|l|u',
      'Scones met jam|luchtige broodjes met room en jam|g|n|om',
    ]],
    ['GR', 'Griekenland', 22, 39.2, [
      'Moussaka|ovenschotel met aubergine en gehakt|l|u',
      'Souvlaki|vleesspiesjes met pitabrood|l|n',
      'Gyros|geroosterd vlees in pitabrood|l|s|ma',
      'Griekse salade|tomaat, komkommer, olijven en feta|g|s|ma',
      'Spanakopita|bladerdeegtaart met spinazie en feta|g|u|ma',
      'Pastitsio|pastaschotel met gehakt en bechamel|l|u',
      'Dolmades|wijnbladeren gevuld met rijst|g|u|m',
      'Gemista|tomaten en paprika gevuld met rijst|g|u',
      'Stifado|rundvlees gestoofd met zilveruitjes|l|u',
      'Tzatziki met brood|yoghurtdip met komkommer en knoflook|g|s|m',
    ]],
    ['TR', 'Turkije', 33.5, 39.5, [
      'Döner kebab|geroosterd vlees van het spit|l|s|ma',
      'Lahmacun|dunne Turkse pizza met gehakt|l|n|ma',
      'Köfte|gekruide gehaktballetjes van de grill|l|n',
      'İskender kebab|döner op brood met tomatensaus en yoghurt|l|n',
      'Menemen|roerei met tomaat en paprika|g|s|o',
      'Mantı|kleine gevulde deegkussentjes met yoghurt|l|u',
      'Pide|bootvormig brood met vulling|l|n',
      'İmam bayıldı|gevulde aubergine met ui en tomaat|g|u',
      'Mercimek çorbası|soep van rode linzen|g|n|ma',
      'Börek|bladerdeeg met kaas en spinazie|g|u|om',
    ]],
  ] },
  azie: { name: 'Azië', box: [28, 148, -11, 52], countries: [
    ['LB', 'Libanon', 36, 34, [
      'Falafel|gefrituurde balletjes van kikkererwten|g|n|ma',
      'Hummus|puree van kikkererwten en tahin|g|s|m',
      'Tabouleh|salade van peterselie, bulgur en tomaat|g|s|m',
      'Shoarma|gekruid vlees in pitabrood|l|n|ma',
      'Kibbeh|gehakt met bulgur, gefrituurd|l|u',
      'Fattoush|salade met gebakken pitabrood|g|s|m',
      'Manakish|plat brood met za\'atar of kaas|g|n|om',
      'Baba ganoush|puree van geroosterde aubergine|g|n|m',
      'Kafta|gekruide gehaktspiesjes|l|n',
      'Mujaddara|linzen met rijst en gebakken ui|g|n',
    ]],
    ['IN', 'India', 78.5, 21.5, [
      'Butter chicken|kip in romige tomatensaus|l|u',
      'Biryani|gekruide rijst met vlees|l|u',
      'Dal|gekruide stoof van linzen|g|n',
      'Palak paneer|spinaziecurry met verse kaas|g|n',
      'Tandoori chicken|gemarineerde kip uit de oven|l|u',
      'Chana masala|curry van kikkererwten|g|n',
      'Samosa|gefrituurd deegpakketje met aardappel|g|u|m',
      'Masala dosa|krokante pannenkoek met aardappelvulling|g|u|om',
      'Rogan josh|lamscurry uit Kasjmir|l|u',
      'Aloo gobi|curry van aardappel en bloemkool|g|n',
    ]],
    ['CN', 'China', 104, 35, [
      'Pekingeend|geroosterde eend met pannenkoekjes|l|u',
      'Dumplings|gestoomde of gebakken deegpakketjes|l|u|ma',
      'Kung pao kip|roerbak van kip, pinda\'s en chilipeper|l|s',
      'Mapo tofu|tofu in pittige saus met gehakt|l|n',
      'Zoetzuur varkensvlees|krokant varkensvlees in zoetzure saus|l|n',
      'Gebakken rijst|rijst uit de wok met ei en groenten|g|s',
      'Chow mein|gebakken noedels met groenten|g|s',
      'Hot pot|samen koken in een pan bouillon|l|u',
      'Loempia\'s|gefrituurde rolletjes met groenten|g|u|m',
      'Wontonsoep|bouillon met gevulde deegkussentjes|l|n|ma',
    ]],
    ['JP', 'Japan', 139, 36.5, [
      'Sushi|rijst met rauwe vis of groenten|v|u',
      'Ramen|noedelsoep met bouillon en toppings|l|u',
      'Tempura|garnalen en groenten in luchtig beslag|v|n',
      'Tonkatsu|gepaneerde varkenskotelet|l|n',
      'Okonomiyaki|hartige pannenkoek met kool|l|n',
      'Yakitori|kipspiesjes van de grill|l|n',
      'Udon|dikke noedels in bouillon|v|n',
      'Japanse curry|milde curry met rijst|l|n',
      'Gyoza|gebakken dumplings|l|u|ma',
      'Misosoep|soep van misopasta met tofu|v|s|om',
    ]],
    ['KR', 'Zuid-Korea', 125, 38, [
      'Bibimbap|rijst met groenten, ei en chilipasta|g|n',
      'Bulgogi|gemarineerd rundvlees van de grill|l|n',
      'Kimchi jjigae|stoofpot van kimchi met tofu|l|n',
      'Koreaanse gefrituurde kip|krokante kip met zoet-pittige saus|l|u',
      'Japchae|glasnoedels met groenten|g|n',
      'Tteokbokki|rijstcakes in pittige saus|v|s|ma',
      'Kimbap|rijstrollen met groenten in zeewier|g|n|m',
      'Samgyeopsal|gegrild buikspek met sla|l|n',
      'Sundubu jjigae|pittige soep met zachte tofu|v|n',
      'Pajeon|hartige pannenkoek met lente-ui|g|s|ma',
    ]],
    ['TH', 'Thailand', 99, 13, [
      'Pad thai|gebakken rijstnoedels met ei en pinda\'s|l|s',
      'Groene curry|curry met kokosmelk en kip|l|n',
      'Tom yum|pittig-zure soep met garnalen|v|n',
      'Massaman curry|milde curry met aardappel en pinda\'s|l|u',
      'Som tam|pittige salade van groene papaja|v|s|m',
      'Pad kra pao|roerbak met basilicum en gehakt|l|s',
      'Tom kha gai|kokossoep met kip|l|n',
      'Khao pad|Thaise gebakken rijst|l|s',
      'Rode curry|pittige curry met kokosmelk|l|n',
      'Mango met kleefrijst|zoete rijst met mango|g|n|m',
    ]],
    ['VN', 'Vietnam', 112, 18, [
      'Pho|noedelsoep met rundvlees en kruiden|l|u',
      'Banh mi|stokbrood met vlees en ingelegde groenten|l|s|m',
      'Verse loempia\'s|rijstvelrolletjes met garnalen en kruiden|v|n|m',
      'Bun cha|gegrild varkensvlees met noedels|l|n',
      'Com tam|gebroken rijst met gegrild vlees|l|n',
      'Bun bo Hue|pittige noedelsoep met rundvlees|l|u',
      'Banh xeo|krokante pannenkoek met garnalen|v|n',
      'Cha gio|gefrituurde loempia\'s|l|u|m',
      'Ca kho to|vis gestoofd in karamelsaus|v|u',
      'Goi ga|frisse salade met kip en kruiden|l|s|m',
    ]],
    ['ID', 'Indonesië', 114, -4, [
      'Nasi goreng|gebakken rijst met ketjap en ei|l|n',
      'Saté|vleesspiesjes met pindasaus|l|n',
      'Rendang|rundvlees lang gestoofd in kokos en kruiden|l|u',
      'Gado gado|groenten met pindasaus|g|n',
      'Bami goreng|gebakken noedels met groenten|l|n',
      'Soto ayam|kippensoep met kurkuma|l|u|ma',
      'Bakso|soep met gehaktballetjes|l|n|ma',
      'Ayam goreng|gefrituurde gemarineerde kip|l|u',
      'Sambal goreng boontjes|pittige roergebakken boontjes|v|s',
      'Tempeh goreng|gebakken tempeh|g|s',
    ]],
  ] },
  afrika: { name: 'Afrika', box: [-32, 68, -37, 38], countries: [
    ['MA', 'Marokko', -7, 31.5, [
      'Tajine met kip|kip gestoofd met citroen en olijven|l|u',
      'Couscous|couscous met groenten en vlees|l|u',
      'Harira|soep van tomaat, linzen en kikkererwten|l|u|ma',
      'Pastilla|hartig-zoete taart met kip en amandel|l|u',
      'Kefta tajine|gehaktballetjes in tomatensaus met ei|l|n',
      'Zaalouk|salade van gestoofde aubergine|g|n|m',
      'Mechoui|langzaam geroosterd lamsvlees|l|u',
      'Bissara|soep van gedroogde tuinbonen|g|u|om',
      'Msemen|gevouwen pannenkoeken|g|u|o',
      'Sardines met chermoula|sardines met kruidenmarinade|v|n',
    ]],
    ['EG', 'Egypte', 30, 26.5, [
      'Koshari|rijst, linzen en pasta met tomatensaus|g|u',
      'Ful medames|gestoofde tuinbonen|g|u|o',
      'Ta\'ameya|falafel van tuinbonen|g|n|om',
      'Molokhia|soep van jutebladeren met kip|l|u',
      'Mahshi|groenten gevuld met rijst|g|u',
      'Fattah|rijst en brood met vlees en knoflooksaus|l|u',
      'Hawawshi|brood gevuld met gekruid gehakt|l|n|ma',
      'Kofta|gehaktspiesjes van de grill|l|n',
      'Shakshuka|eieren in tomatensaus|g|n|om',
      'Om ali|warme broodpudding met noten|g|n|m',
    ]],
    ['ET', 'Ethiopië', 39.5, 8.5, [
      'Injera met wat|zuurdesempannenkoek met stoofpotjes|l|u',
      'Doro wat|pittige kipstoof met ei|l|u',
      'Tibs|gebakken stukjes vlees met ui|l|n',
      'Shiro|stoof van kikkererwtenmeel|g|n',
      'Misir wat|pittige stoof van rode linzen|g|n',
      'Kitfo|fijngehakt rundvlees met kruidenboter|l|s',
      'Gomen|gestoofde boerenkool|g|n',
      'Firfir|stukjes injera in pittige saus|g|s|o',
      'Atkilt wat|kool, wortel en aardappel met kurkuma|g|n',
      'Sambusa|gefrituurd deegpakketje met linzen|g|u|m',
    ]],
    ['ZA', 'Zuid-Afrika', 24, -29, [
      'Bobotie|gekruid gehakt uit de oven met ei|l|u',
      'Braai|vlees van de barbecue|l|u',
      'Bunny chow|uitgehold brood gevuld met curry|l|u',
      'Boerewors|gekruide worst van de grill|l|n',
      'Potjiekos|stoofpot uit een gietijzeren pot|l|u',
      'Pap en vleis|maïspap met vlees en saus|l|n',
      'Chakalaka|pittige groentestoof met bonen|g|n',
      'Sosaties|gemarineerde vleesspiesjes|l|u',
      'Tamatiebredie|lamsstoof met tomaat|l|u',
      'Malvapudding|warme zoete pudding|g|u|m',
    ]],
  ] },
  'noord-amerika': { name: 'Noord-Amerika', box: [-135, -60, 8, 55], countries: [
    ['US', 'Verenigde Staten', -98, 39, [
      'Hamburger|broodje met een burger van rundvlees|l|n',
      'Mac and cheese|macaroni in kaassaus|g|n',
      'Barbecue ribs|varkensribben met barbecuesaus|l|u',
      'Buffalo wings|pittige kippenvleugels|l|u',
      'Clam chowder|romige soep met schelpdieren|v|u|ma',
      'Hotdog|broodje worst met saus|l|s|m',
      'Pancakes met ahornsiroop|dikke luchtige pannenkoeken|g|n|o',
      'Fried chicken|krokant gefrituurde kip|l|u',
      'Caesarsalade|sla met kip, croutons en dressing|l|s|ma',
      'Jambalaya|rijst met worst, kip en garnalen|l|u',
    ]],
    ['MX', 'Mexico', -102, 23.5, [
      'Taco\'s|kleine tortilla\'s met vlees en salsa|l|n',
      'Enchiladas|gevulde tortilla\'s met saus uit de oven|l|u',
      'Guacamole met tortillachips|dip van avocado|g|s|m',
      'Quesadilla|tortilla met gesmolten kaas|g|s|ma',
      'Pozole|soep van maïs en varkensvlees|l|u',
      'Burrito|grote tortilla met rijst, bonen en vlees|l|n',
      'Mole poblano|kip in saus van chili en chocolade|l|u',
      'Tamales|gestoomd maïsdeeg met vulling|l|u',
      'Huevos rancheros|gebakken eieren op tortilla met salsa|g|s|o',
      'Sopa de tortilla|tomatensoep met reepjes tortilla|l|n|ma',
    ]],
  ] },
  'zuid-amerika': { name: 'Zuid-Amerika', box: [-105, -15, -56, 14], countries: [
    ['SR', 'Suriname', -56, 4.5, [
      'Roti|platbrood met kip, aardappel en kousenband|l|u',
      'Pom|ovenschotel van pomtajer en kip|l|u',
      'Moksi alesi|gemengde rijst met vlees of vis|l|u',
      'Saoto soep|kippensoep met taugé en ei|l|u|ma',
      'Surinaamse nasi met kip|gebakken rijst met kip|l|u',
      'Surinaamse bami|gebakken noedels met kip|l|n',
      'Bruine bonen met rijst|bruine bonen met zoutvlees|l|u',
      'Bara|gefrituurd broodje van linzenmeel|g|u|m',
      'Pindasoep|soep van pindakaas met kip|l|u',
      'Her\'heri|gekookte knollen en banaan met bakkeljauw|v|u',
    ]],
    ['BR', 'Brazilië', -50, -12, [
      'Feijoada|stoofpot van zwarte bonen en vlees|l|u',
      'Churrasco|vlees van de grill|l|u',
      'Moqueca|visstoof met kokosmelk|v|n',
      'Pão de queijo|kaasbroodjes van tapiocameel|g|n|om',
      'Coxinha|gefrituurde kroket met kip|l|u|m',
      'Feijão tropeiro|bonen met worst en cassavemeel|l|n',
      'Bobó de camarão|garnalen in cassavepuree|v|u',
      'Acarajé|gefrituurd bonenbroodje met garnalen|v|u|m',
      'Arroz com feijão|rijst met bonen|g|n',
      'Picanha|staartstuk van de grill|l|n',
    ]],
    ['AR', 'Argentinië', -65, -35, [
      'Asado|vlees van de houtskoolgrill|l|u',
      'Empanadas|deegflapjes gevuld met vlees|l|u|ma',
      'Milanesa|gepaneerde lap vlees|l|n',
      'Choripán|broodje chorizo met chimichurri|l|s|m',
      'Locro|stevige soep van maïs en vlees|l|u',
      'Provoleta|gegrilde provolonekaas|g|s|m',
      'Bife de chorizo|entrecote van de grill|l|n',
      'Humita|maïspuree gestoomd in maïsblad|g|u',
      'Carbonada|stoofpot met vlees, pompoen en maïs|l|u',
      'Ñoquis|gnocchi met tomatensaus|g|n',
    ]],
    ['PE', 'Peru', -76, -10, [
      'Ceviche|rauwe vis gemarineerd in limoensap|v|n',
      'Lomo saltado|roerbak van rundvlees met friet|l|n',
      'Ají de gallina|kip in romige pepersaus|l|u',
      'Anticuchos|gegrilde vleesspiesjes|l|n',
      'Causa|aardappeltaartje met tonijn|v|n|m',
      'Papa a la huancaína|aardappels met pittige kaassaus|g|n|m',
      'Arroz con pollo|rijst met kip en koriander|l|u',
      'Rocoto relleno|gevulde pittige paprika|l|u',
      'Pollo a la brasa|kip van het spit|l|u',
      'Tacu tacu|gebakken koek van rijst en bonen|g|n',
    ]],
  ] },
  oceanie: { name: 'Oceanië', box: [105, 180, -48, 2], countries: [
    ['AU', 'Australië', 134, -25, [
      'Meat pie|pasteitje met rundvlees en jus|l|u|ma',
      'Barramundi|gegrilde witvis|v|n',
      'Chicken parmigiana|gepaneerde kip met tomatensaus en kaas|l|n',
      'Sausage sizzle|worstje op brood met ui|l|s|m',
      'Fish and chips|gefrituurde vis met dikke frieten|v|n',
      'Lamsbout uit de oven|gebraden lamsvlees met groenten|l|u',
      'Vegemite op toast|toast met hartige gistpasta|g|s|o',
      'Pavlova|schuimtaart met room en fruit|g|u|m',
      'Kangoeroesteak|mager vlees van de grill|l|s',
      'Damper|brood gebakken in de hete as|g|u|m',
    ]],
  ] },
};
